Repository danforthcenter/plantcv, pull requests merged in 2018-03, with the labels that each got.

#217 Enhanceboundary
  plantcv/__init__.py
  plantcv/analyze_bound.py
  plantcv/analyze_bound_horizontal.py
  plantcv/analyze_bound_vertical.py
  tests/data/input_binary_img.png
  tests/data/input_contours.npz
  tests/data/input_contours1.npz
  tests/tests.py
Labels: enhancement

#222 Updated installation documentation
  docs/installation.md
Labels: documentation

#224 Disabled warnings for matplotlib.use
  plantcv/analyze_NIR_intensity.py
  plantcv/analyze_color.py
  plantcv/fluor_fvfm.py
  plantcv/learn/naive_bayes.py
  plantcv/plot_colorbar.py
  plantcv/plot_hist.py
  plantcv/triangle_auto_threshold.py
  tests/tests.py
Labels: bug
