Repository danforthcenter/plantcv, pull requests merged in 2018-10, with the labels that each got.

#261 Fill function update
  mkdocs.yml
  plantcv/plantcv/fill.py
  tests/tests.py
Labels: enhancement

#263 Update mkdocs.yml
  mkdocs.yml
Labels: bugfix

#262 update median_blur function
  docs/median_blur.md
  plantcv/plantcv/median_blur.py
  tests/tests.py
Labels: enhancement, new feature

#264 Explicitly define readthedocs theme
  mkdocs.yml
Labels: bugfix
