Repository danforthcenter/plantcv, pull requests merged in 2019-06, with the labels that each got.

#383 Misc corrections
  docs/machine_learning_tutorial.md
  docs/morphology_tutorial.md
  docs/multi-plant_tutorial.md
  docs/nir_tutorial.md
  docs/psII_tutorial.md
  docs/transform_color_correction_tutorial.md
  docs/vis_nir_tutorial.md
  docs/vis_tutorial.md
  mask-images/test.png
  ori-images/test.png
  plantcv/plantcv/morphology/check_cycles.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
Labels: bugfix

#387 Use OpenCV calcHist method
  plantcv/plantcv/analyze_nir_intensity.py
Labels: bugfix

#388 minor enhancements
  docs/CONTRIBUTING.md
  docs/analysis_approach.md
  docs/analyze_color.md
  docs/fill_holes.md
  docs/img/documentation_images/fill_holes/fill_holes_mask.jpg
  docs/img/documentation_images/fill_holes/filled_holes.jpg
  docs/jupyter.md
  docs/morphology_tutorial.md
  docs/pipeline_parallel.md
  docs/roi_objects.md
  docs/transform_color_correction_tutorial.md
  docs/updating.md
  docs/visualize_histogram.md
  environment.yml
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/fill_holes.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/roi_objects.py
  requirements.txt
  tests/tests.py
Labels: bugfix, enhancement, new feature

#390 Morphology prune2.0 and add segment_combine
  docs/img/documentation_images/combine_segments/combined2_img.jpg
  docs/img/documentation_images/combine_segments/combined_img.jpg
  docs/img/documentation_images/combine_segments/labeled_ids_img.jpg
  docs/img/documentation_images/prune/debugging_pruned_image.jpg
  docs/img/documentation_images/prune/pruned_debug_img.jpg
  docs/img/documentation_images/prune/pruned_debug_img_mask.jpg
  docs/img/documentation_images/prune/pruned_segmented_img.jpg
  docs/img/documentation_images/prune/pruned_segmented_img_mask.jpg
  docs/img/documentation_images/prune/pruned_skeleton.jpg
  docs/img/documentation_images/prune/pruned_skeleton_img.jpg
  docs/img/documentation_images/prune/skeleton_image.jpg
  docs/img/documentation_images/prune/skeleton_img.jpg
  docs/img/tutorial_images/morphology/pruned_debug_img_mask_tutorial.jpg
  docs/img/tutorial_images/morphology/pruned_segmented_img_mask_tutorial.jpg
  docs/morphology_tutorial.md
  docs/prune.md
  docs/segment_combine.md
  docs/segment_curvature.md
  docs/segment_euclidean_length.md
  docs/segment_id.md
  docs/segment_insertion_angle.md
  docs/segment_pathlength.md
  docs/segment_skeleton.md
  docs/segment_sort.md
  docs/segment_tangent_angle.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/morphology/__init__.py
  plantcv/plantcv/morphology/_iterative_prune.py
  plantcv/plantcv/morphology/prune.py
  plantcv/plantcv/morphology/segment_combine.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_skeleton.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  plantcv/plantcv/print_image.py
  tests/tests.py
Labels: enhancement, new feature

#393 Add json to table method
  MANIFEST.in
  docs/output_measurements.md
  docs/pipeline_parallel.md
  docs/tools.md
  docs/within_frame.md
  mkdocs.yml
  plantcv-train.py
  plantcv-utils.py
  plantcv-workflow.py
  plantcv/parallel/job_builder.py
  plantcv/parallel/parsers.py
  plantcv/parallel/process_results.py
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/print_results.py
  plantcv/utils/__init__.py
  plantcv/utils/converters.py
  setup.py
  tests/data/data_results.txt
  tests/data/incorrect_json_data.txt
  tests/data/merged_output.json
  tests/parallel_data/appended_results.json
  tests/parallel_data/new_result.json
  tests/parallel_data/results/VIS_SV_0_z1_h1_g0_e82_117770.jpg.txt
  tests/tests.py
Labels: bugfix, new feature

#394 Allows custom padding in visualize pseudocolor
  docs/roi_objects.md
  docs/visualize_pseudocolor.md
  plantcv/plantcv/analyze_object.py
  plantcv/plantcv/object_composition.py
  plantcv/plantcv/visualize/pseudocolor.py
  tests/tests.py
Labels: documentation, enhancement, new feature

#400 Bug fix list observations
  plantcv/plantcv/x_axis_pseudolandmarks.py
  plantcv/plantcv/y_axis_pseudolandmarks.py
  plantcv/utils/converters.py
Labels: bugfix
