Repository danforthcenter/plantcv, pull requests merged in 2019-08, with the labels that each got.

#425 Nonuniform lighting correction
  docs/img/documentation_images/nonuniform_illumination/corrected_img.jpg
  docs/img/documentation_images/nonuniform_illumination/working_video.png
  docs/morphology_tutorial.md
  docs/nonuniform_illumination.md
  docs/pipeline_parallel.md
  docs/rectangle_mask.md
  docs/updating.md
  mkdocs.yml
  plantcv/parallel/process_results.py
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/nonuniform_illumination.py
  plantcv/plantcv/transform/rescale.py
  tests/tests.py
Labels: new feature

#429 Remove version restriction
  docs/closing.md
  docs/get_kernel.md
  docs/opening.md
  environment.yml
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/get_kernel.py
  requirements.txt
  tests/tests.py
Labels: bugfix, documentation, new feature

#433 Misc function improvements
  docs/segment_sort.md
  plantcv/plantcv/morphology/__init__.py
  plantcv/plantcv/morphology/_iterative_prune.py
  plantcv/plantcv/morphology/prune.py
  plantcv/plantcv/morphology/segment_id.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_sort.py
  tests/tests.py
Labels: enhancement
