Repository danforthcenter/plantcv, pull requests merged in 2019-01, with the labels that each got.

#289 Update tests
  plantcv/plantcv/__init__.py
  plantcv/plantcv/gaussian_blur.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/white_balance.py
  tests/data/cluster_names_too_many.txt
  tests/data/naive_bayes_pdfs_bad.txt
  tests/tests.py
Labels: enhancement

#292 add git tag regex to build rules
  .travis.yml
Labels: bugfix

#294 Render from markdown in PyPI
  MANIFEST.in
  setup.py
Labels: bugfix

#299 Add pypi and conda install instructions
  .travis.yml
  README.md
  docs/installation.md
  environments/environment27.yml
Labels: new feature

#300 Use pypi for travis builds
  .travis.yml
  docs/installation.md
  environment.yml
  environments/environment27.yml
  environments/environment36.yml
  requirements.txt
Labels: testing

#301 Interactive docs, plus some tutorial and docs corrections
  README.md
  docs/analyze_NIR_intensity.md
  docs/flip.md
  docs/index.md
  docs/nir_tutorial.md
  docs/rectangle_mask.md
  docs/report_size_marker.md
  docs/roi_objects.md
  docs/scharr_filter.md
  docs/sobel_filter.md
  docs/transform_correct_color.md
  docs/vis_nir_tutorial.md
Labels: documentation

#302 add texture function
  README.md
  docs/img/documentation_images/texture_threshold/texture_gray.jpg
  docs/img/documentation_images/texture_threshold/texture_thresholded.jpg
  docs/texture_threshold.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/threshold/__init__.py
  plantcv/plantcv/threshold/threshold_methods.py
  tests/data/input_gray_img_small.jpg
  tests/tests.py
Labels: new feature

#303 debug='print' option
  plantcv/plantcv/x_axis_pseudolandmarks.py
  plantcv/plantcv/y_axis_pseudolandmarks.py
  tests/tests.py
Labels: enhancement

#305 Add canny function
  docs/canny_edge_detect.md
  docs/img/documentation_images/canny_edge_detect/default_canny.jpg
  docs/img/documentation_images/canny_edge_detect/low_sigma_canny.jpg
  docs/img/documentation_images/canny_edge_detect/mask_canny.jpg
  docs/img/documentation_images/canny_edge_detect/masked_img_canny.jpg
  docs/img/documentation_images/canny_edge_detect/original_image.jpg
  docs/texture_threshold.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/acute.py
  plantcv/plantcv/canny_edge_detect.py
  tests/tests.py
Labels: new feature

#312 Pseudocolor grayscale images function
  .travis.yml
  docs/analyze_NIR_intensity.md
  docs/img/documentation_images/pseudocolor/mask.jpg
  docs/img/documentation_images/pseudocolor/original_grayscale.jpg
  docs/img/documentation_images/pseudocolor/pseudo_img.jpg
  docs/img/documentation_images/pseudocolor/pseudo_nomask.jpg
  docs/pseudocolor.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/plot_image.py
  plantcv/plantcv/pseudocolor.py
  plantcv/plantcv/threshold/threshold_methods.py
  tests/tests.py
Labels: New Function Proposal, new feature

#313 Remove Agg backend in plot
  plantcv/plantcv/plot_image.py
Labels: bugfix
