Repository danforthcenter/plantcv, pull requests merged in 2019-07, with the labels that each got.

#416 Update docker image
  Dockerfile
  docs/installation.md
Labels: bugfix, documentation

#417 add thermal tutorial to table of contents
  mkdocs.yml
Labels: documentation

#418 Restore pseudocolor mask functionality
  plantcv/plantcv/visualize/pseudocolor.py
Labels: bugfix

#419 Random image sampling function
  docs/img/documentation_images/roi_custom/custom_roi.jpg
  docs/img/documentation_images/roi_custom/rgb_img.jpg
  docs/roi_custom.md
  docs/thermal_tutorial.md
  docs/tools.md
  docs/transform_rescale.md
  mkdocs.yml
  plantcv-utils.py
  plantcv/plantcv/roi/__init__.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/utils/__init__.py
  plantcv/utils/sample_images.py
  tests/parallel_data/snapshots/snapshot57381/NIR_SV_0_z1_h1_g0_e65_117779.jpg
  tests/parallel_data/snapshots/snapshot57381/VIS_SV_0_z1_h1_g0_e82_117770.jpg
  tests/parallel_data/snapshots/snapshot57382/NIR_SV_0_z1_h1_g0_e65_117779.jpg
  tests/parallel_data/snapshots/snapshot57382/VIS_SV_0_z1_h1_g0_e82_117770.jpg
  tests/tests.py
Labels: documentation, new feature

#421 update roi_objects
  plantcv/plantcv/roi_objects.py
  tests/tests.py
Labels: bugfix, enhancement
