Repository danforthcenter/plantcv, pull requests merged in 2019-10, with the labels that each got.

#456 Update apply mask
  plantcv/plantcv/apply_mask.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  tests/hyperspectral_data/darkReference
  tests/hyperspectral_data/darkReference.hdr
  tests/tests.py
Labels: bugfix, enhancement, new feature

#460 Hyperspectral group dev
  plantcv/plantcv/analyze_thermal_values.py
  plantcv/plantcv/apply_mask.py
  plantcv/plantcv/hyperspectral/__init__.py
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  plantcv/plantcv/hyperspectral/extract_index.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  tests/hyperspectral_data/darkReference.hdr
  tests/hyperspectral_data/darkReference_mask.png
  tests/tests.py
  vice/Dockerfile
Labels: enhancement, new feature, testing

#463 Hyperspectral group dev
  plantcv/plantcv/hyperspectral/analyze_spectral.py
Labels: bugfix

#467 Update process_results to bypass missing metadata bug
  plantcv/parallel/process_results.py
Labels: bugfix

#457 Doc updates
  docs/installation.md
  docs/outputs.md
  docs/pipeline_parallel.md
  plantcv-workflow.py
Labels: documentation

#459 Sample images fix
  plantcv-utils.py
  plantcv/utils/sample_images.py
Labels: bugfix, documentation

#475 Add Spectral_data class
  plantcv/plantcv/__init__.py
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  plantcv/plantcv/hyperspectral/extract_index.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/readimage.py
  tests/hyperspectral_data/darkReference2.hdr
  tests/tests.py
Labels: enhancement

#454 Add regular expression-based metadata parser option to plantcv.parallel
  docs/pipeline_parallel.md
  plantcv-workflow.py
  plantcv/parallel/parsers.py
  tests/tests.py
Labels: new feature

#480 Fix plantcv-workflow help function
  plantcv-workflow.py
Labels: bugfix
