Repository danforthcenter/plantcv, pull requests merged in 2019-09, with the labels that each got.

#436 Enhance pcv.roi_objects
  docs/multi-plant_tutorial.md
  docs/roi_multi.md
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/cluster_contours.py
  plantcv/plantcv/roi_objects.py
  plantcv/plantcv/transform/color_correction.py
  tests/tests.py
Labels: enhancement

#439 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/something-is-not-working.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#440 Add docs extension
  .github/PULL_REQUEST_TEMPLATE.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#445 Remove hyphens in datetime
  plantcv/parallel/parsers.py
  plantcv/plantcv/analyze_color.py
Labels: bugfix

#446 Read ENVI hyperspectral data
  plantcv/plantcv/__init__.py
  plantcv/plantcv/hyperspectral/__init__.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/readimage.py
  tests/data/target_img.png
  tests/hyperspectral_data/darkReference
  tests/hyperspectral_data/darkReference.hdr
  tests/hyperspectral_data/darkReference2
  tests/hyperspectral_data/darkReference2.hdr
  tests/hyperspectral_data/darkReference3
  tests/hyperspectral_data/darkReference3.hdr
  tests/tests.py
Labels: new feature, work in progress

#449 Extract spectral indices
  plantcv/plantcv/hyperspectral/__init__.py
  plantcv/plantcv/hyperspectral/extract_index.py
  tests/tests.py
Labels: new feature

#451 Add Dockerfile
  vice/Dockerfile
Labels: new feature
