Repository danforthcenter/plantcv, pull requests merged in 2019-03, with the labels that each got.

#336 Auto_crop image option
  docs/auto_crop.md
  docs/img/documentation_images/auto_crop/155_auto_cropped.jpg
  docs/img/documentation_images/auto_crop/155_auto_image.jpg
  plantcv/plantcv/auto_crop.py
  tests/tests.py
Labels: enhancement

#337 Uppercase string parameters
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/apply_mask.py
  plantcv/plantcv/auto_crop.py
  plantcv/plantcv/canny_edge_detect.py
  plantcv/plantcv/crop_position_mask.py
  plantcv/plantcv/flip.py
  plantcv/plantcv/get_nir.py
  plantcv/plantcv/rectangle_mask.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/rgb2gray_hsv.py
  plantcv/plantcv/rgb2gray_lab.py
  plantcv/plantcv/roi_objects.py
  plantcv/plantcv/shift_img.py
  plantcv/plantcv/white_balance.py
  tests/tests.py
Labels: enhancement, testing

#338 Pseudocolor background=white & testing
  docs/img/documentation_images/pseudocolor/pseudo_cropped.jpg
  docs/pseudocolor.md
  plantcv/plantcv/acute.py
  plantcv/plantcv/acute_vertex.py
  plantcv/plantcv/analyze_object.py
  plantcv/plantcv/cluster_contours.py
  plantcv/plantcv/landmark_reference_pt_dist.py
  plantcv/plantcv/pseudocolor.py
  plantcv/plantcv/threshold/threshold_methods.py
  tests/data/target_img copy.png
  tests/tests.py
Labels: enhancement

#339 Fix mkdocs builds on Read the Docs
  docs/requirements.txt
  docs/scripts/color_correction_script.md
  docs/scripts/machine_learning_script.md
  docs/scripts/multi-plant_script.md
  docs/scripts/nir_script.md
  docs/scripts/psII_script.md
  docs/scripts/vis_nir_script.md
  docs/scripts/vis_script.md
  mkdocs.yml
Labels: bugfix

#340 Missing string generalizations
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/auto_crop.py
  plantcv/plantcv/pseudocolor.py
  tests/tests.py
Labels: enhancement

#341 standardize argument order/names
  docs/acute_vertex.md
  docs/auto_crop.md
  docs/canny_edge_detect.md
  docs/dilate.md
  docs/erode.md
  docs/gaussian_blur.md
  docs/laplace_filter.md
  docs/median_blur.md
  docs/pseudocolor.md
  docs/scale_features.md
  docs/sobel_filter.md
  docs/texture_threshold.md
  docs/updating.md
  docs/x_axis_pseudolandmarks.md
  docs/y_axis_pseudolandmarks.md
  plantcv/plantcv/acute.py
  plantcv/plantcv/acute_vertex.py
  plantcv/plantcv/auto_crop.py
  plantcv/plantcv/canny_edge_detect.py
  plantcv/plantcv/dilate.py
  plantcv/plantcv/erode.py
  plantcv/plantcv/gaussian_blur.py
  plantcv/plantcv/laplace_filter.py
  plantcv/plantcv/pseudocolor.py
  plantcv/plantcv/readimage.py
  plantcv/plantcv/rectangle_mask.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/scale_features.py
  plantcv/plantcv/shift_img.py
  plantcv/plantcv/sobel_filter.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/white_balance.py
  plantcv/plantcv/x_axis_pseudolandmarks.py
  plantcv/plantcv/y_axis_pseudolandmarks.py
  tests/tests.py
Labels: documentation

#342 plot_hist function
  docs/img/documentation_images/plot_hist/01_hsv_saturation.jpg
  docs/img/documentation_images/plot_hist/hist.jpg
  docs/img/documentation_images/plot_hist/mask.jpg
  docs/multi-plant_tutorial.md
  docs/nir_tutorial.md
  docs/plot_hist.md
  docs/roi_multi.md
  docs/updating.md
  docs/vis_nir_tutorial.md
  docs/vis_tutorial.md
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/plot_hist.py
  tests/tests.py
Labels: New Function Proposal, documentation, enhancement

#343 Cluster function show_grid
  docs/cluster_contours.md
  docs/img/documentation_images/cluster_contour/show_grid.jpg
  docs/multi-plant_tutorial.md
  docs/updating.md
  plantcv/plantcv/cluster_contours.py
  tests/tests.py
Labels: enhancement

#346 Bug! should be params.debug_outdir to print
  plantcv/plantcv/dilate.py
  plantcv/plantcv/erode.py
  plantcv/plantcv/plot_hist.py
  tests/tests.py
Labels: bug, enhancement

#350 Add visualize sub-package, colorize_masks, & small corrections
  docs/analyze_NIR_intensity.md
  docs/fluor_fvfm.md
  docs/img/documentation_images/colorize_masks/available_colors.jpg
  docs/img/documentation_images/colorize_masks/background.jpg
  docs/img/documentation_images/colorize_masks/chlorosis.jpg
  docs/img/documentation_images/colorize_masks/colored_classes.jpg
  docs/img/documentation_images/colorize_masks/plant.jpg
  docs/img/documentation_images/colorize_masks/pustule.jpg
  docs/img/documentation_images/histogram/01_hsv_saturation.jpg
  docs/img/documentation_images/histogram/grayscale_image.jpg
  docs/img/documentation_images/histogram/hist.jpg
  docs/img/documentation_images/histogram/histogram.jpg
  docs/img/documentation_images/histogram/mask.jpg
  docs/machine_learning_tutorial.md
  docs/multi-plant_tutorial.md
  docs/naive_bayes_multiclass.md
  docs/nir_tutorial.md
  docs/print_image.md
  docs/psII_tutorial.md
  docs/roi_circle.md
  docs/roi_ellipse.md
  docs/roi_from_binary_image.md
  docs/roi_multi.md
  docs/roi_rectangle.md
  docs/rotate2.md
  docs/scale_features.md
  docs/updating.md
  docs/vis_nir_tutorial.md
  docs/vis_tutorial.md
  docs/visualize_colorize_masks.md
  docs/visualize_histogram.md
  docs/visualize_pseudocolor.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/crop_position_mask.py
  plantcv/plantcv/landmark_reference_pt_dist.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/rotate.py
  plantcv/plantcv/visualize/__init__.py
  plantcv/plantcv/visualize/colorize_masks.py
  plantcv/plantcv/visualize/histogram.py
  plantcv/plantcv/visualize/pseudocolor.py
  plantcv/plantcv/x_axis_pseudolandmarks.py
  plantcv/plantcv/y_axis_pseudolandmarks.py
  tests/tests.py
Labels: New Function Proposal, bugfix, documentation, new feature

#351 Visualize functions options
  docs/updating.md
  docs/visualize_histogram.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/visualize/colorize_masks.py
  plantcv/plantcv/visualize/histogram.py
  tests/tests.py
Labels: enhancement

#352 opening/closing function & unit testing
  docs/closing.md
  docs/cluster_contours_splitimg.md
  docs/img/documentation_images/closing/after_closing.jpg
  docs/img/documentation_images/closing/before_closing.jpg
  docs/img/documentation_images/opening/after_opening.jpg
  docs/img/documentation_images/opening/before_opening.jpg
  docs/multi-plant_tutorial.md
  docs/opening.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/closing.py
  plantcv/plantcv/cluster_contour_splitimg.py
  plantcv/plantcv/opening.py
  plantcv/plantcv/watershed.py
  tests/tests.py
Labels: New Function Proposal, enhancement

#354 add threshold.custom_range
  docs/custom_range_threshold.md
  docs/img/documentation_images/custom_range_threshold/gray_mask.jpg
  docs/img/documentation_images/custom_range_threshold/gray_masked.jpg
  docs/img/documentation_images/custom_range_threshold/gray_original.jpg
  docs/img/documentation_images/custom_range_threshold/hsv_mask.jpg
  docs/img/documentation_images/custom_range_threshold/hsv_masked.jpg
  docs/img/documentation_images/custom_range_threshold/hsv_original.jpg
  docs/img/documentation_images/custom_range_threshold/lab_mask.jpg
  docs/img/documentation_images/custom_range_threshold/lab_masked.jpg
  docs/img/documentation_images/custom_range_threshold/lab_original.jpg
  docs/img/documentation_images/custom_range_threshold/rgb_mask.jpg
  docs/img/documentation_images/custom_range_threshold/rgb_masked.jpg
  docs/img/documentation_images/custom_range_threshold/rgb_original.jpg
  docs/nir_tutorial.md
  docs/read_image.md
  mkdocs.yml
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/readimage.py
  plantcv/plantcv/threshold/__init__.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/visualize/histogram.py
  tests/data/input_rgba.png
  tests/tests.py
Labels: New Function Proposal, enhancement, new feature

#355 keep 1st generation sub contours when using 'largest' in roi_objects
  plantcv/plantcv/dilate.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/roi_objects.py
Labels: enhancement
