Repository danforthcenter/plantcv, pull requests merged in 2019-02, with the labels that each got.

#315 Update analyze functions outputs
  docs/analyze_NIR_intensity.md
  docs/analyze_bound_horizontal.md
  docs/analyze_bound_vertical.md
  docs/analyze_color.md
  docs/analyze_shape.md
  docs/fluor_fvfm.md
  docs/img/documentation_images/fluor_fvfm/fvfm_histogram.jpg
  docs/nir_tutorial.md
  docs/psII_tutorial.md
  docs/updating.md
  docs/vis_nir_tutorial.md
  docs/vis_tutorial.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/analyze_bound_horizontal.py
  plantcv/plantcv/analyze_bound_vertical.py
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/analyze_object.py
  plantcv/plantcv/fluor_fvfm.py
  plantcv/plantcv/plot_colorbar.py
  plantcv/plantcv/watershed.py
  tests/tests.py
Labels: enhancement

#317 Extend filetypes for plot and print functions
  docs/img/documentation_images/pseudocolor/pseudo_black_bkgd.jpg
  docs/img/documentation_images/pseudocolor/pseudo_cropped.jpg
  docs/print_image.md
  docs/pseudocolor.md
  plantcv/plantcv/fluor_fvfm.py
  plantcv/plantcv/plot_image.py
  plantcv/plantcv/print_image.py
  plantcv/plantcv/pseudocolor.py
  tests/tests.py
Labels: enhancement

#326 Add background option to pseudocolor
  docs/img/documentation_images/pseudocolor/mask.jpg
  docs/img/documentation_images/pseudocolor/original_grayscale.jpg
  docs/img/documentation_images/pseudocolor/pseudo_black_bkgd.jpg
  docs/img/documentation_images/pseudocolor/pseudo_cropped.jpg
  docs/img/documentation_images/pseudocolor/pseudo_img.jpg
  docs/img/documentation_images/pseudocolor/pseudo_onimage.jpg
  docs/pseudocolor.md
  plantcv/plantcv/print_image.py
  plantcv/plantcv/pseudocolor.py
  tests/tests.py
Labels: enhancement

#323 Multiple ROI Function
  docs/img/documentation_images/multi/custom_list_roi.jpg
  docs/img/documentation_images/multi/first_plant_mask.jpg
  docs/img/documentation_images/multi/first_plant_object.jpg
  docs/img/documentation_images/multi/first_plant_shape.jpg
  docs/img/documentation_images/multi/grid_roi.jpg
  docs/img/documentation_images/multi/multi_plants_shape.jpg
  docs/img/documentation_images/multi/original_multi_image.jpg
  docs/roi_multi.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/roi/__init__.py
  plantcv/plantcv/roi/roi_methods.py
  tests/tests.py
Labels: New Function Proposal, new feature

#327 Update matplotlib imports
  plantcv/learn/__init__.py
  plantcv/learn/naive_bayes.py
  plantcv/plantcv/__init__.py
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/fluor_fvfm.py
  plantcv/plantcv/plot_hist.py
  plantcv/plantcv/plot_image.py
  plantcv/plantcv/print_image.py
  plantcv/plantcv/pseudocolor.py
  plantcv/plantcv/threshold/threshold_methods.py
  tests/tests.py
Labels: bugfix

#328 Keep largest contour
  docs/index.md
  docs/machine_learning_tutorial.md
  docs/multi-plant_tutorial.md
  docs/nir_tutorial.md
  docs/psII_tutorial.md
  docs/roi_multi.md
  docs/roi_objects.md
  docs/scripts/color_correction_script.md
  docs/transform_color_correction_tutorial.md
  docs/vis_nir_tutorial.md
  docs/vis_tutorial.md
  plantcv/plantcv/roi_objects.py
  tests/tests.py
Labels: enhancement

#332 Add debug analyze_color & update analyze_bound_horizontal
  docs/analyze_bound_horizontal.md
  plantcv/plantcv/analyze_bound_horizontal.py
  plantcv/plantcv/analyze_color.py
  tests/tests.py
Labels: enhancement

#334 Add link to hyperspectral docs
  mkdocs.yml
Labels: documentation

#335 line_thickness parameter
  docs/img/documentation_images/params/default_thickness.jpg
  docs/img/documentation_images/params/thickness3.jpg
  docs/index.md
  docs/params.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/acute_vertex.py
  plantcv/plantcv/analyze_bound_horizontal.py
  plantcv/plantcv/analyze_bound_vertical.py
  plantcv/plantcv/analyze_object.py
  plantcv/plantcv/object_composition.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/roi_objects.py
  plantcv/plantcv/scale_features.py
  plantcv/plantcv/x_axis_pseudolandmarks.py
  plantcv/plantcv/y_axis_pseudolandmarks.py
Labels: enhancement
