Repository danforthcenter/plantcv, pull requests merged in 2020-02, with the labels that each got.

#522 Update hyperspectral analyze_index to add histogram
  docs/analyze_index.md
  docs/img/documentation_images/analyze_index/index_ndvi_hist.jpg
  docs/updating.md
  plantcv/plantcv/hyperspectral/analyze_index.py
  tests/tests.py
Labels: enhancement

#528 Add visualize colorspaces
  docs/img/documentation_images/visualize_colorspaces/all_colorspaces.jpg
  docs/updating.md
  docs/visualize_colorspace.md
  plantcv/plantcv/visualize/__init__.py
  plantcv/plantcv/visualize/colorspaces.py
  tests/tests.py
Labels: enhancement, new feature

#526 Update hyper analyze index hist
  docs/analyze_index.md
  docs/updating.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/canny_edge_detect.py
  plantcv/plantcv/hyperspectral/analyze_index.py
  plantcv/plantcv/hyperspectral/calibrate.py
  plantcv/plantcv/hyperspectral/extract_index.py
  plantcv/plantcv/hyperspectral/extract_wavelength.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/transform/color_correction.py
  tests/tests.py
Labels: enhancement, new feature

#527 Add pri index
  docs/extract_index.md
  plantcv/plantcv/hyperspectral/extract_index.py
  plantcv/plantcv/hyperspectral/read_data.py
  tests/tests.py
Labels: enhancement

#530 Update dependencies
  .travis.yml
  requirements.txt
Labels: enhancement, work in progress

#529 roi2contour
  docs/img/documentation_images/roi2mask/custom_mask.jpg
  docs/img/documentation_images/roi2mask/custom_roi.jpg
  docs/roi2mask.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/roi/__init__.py
  plantcv/plantcv/roi/roi2mask.py
  plantcv/plantcv/visualize/colorspaces.py
  plantcv/plantcv/visualize/histogram.py
  tests/tests.py
Labels: enhancement, new feature
