Repository danforthcenter/plantcv, pull requests merged in 2020-03, with the labels that each got.

#535 Analyze index march2020 updates
  docs/analyze_index.md
  docs/updating.md
  plantcv/plantcv/hyperspectral/analyze_index.py
  plantcv/plantcv/hyperspectral/extract_index.py
  tests/tests.py
Labels: bugfix, enhancement

#540 force min/max bin values to float datatype in analyze_index
  plantcv/plantcv/hyperspectral/analyze_index.py
Labels: bugfix

#542 Fix missing docs pages
  docs/hyperspectral_tutorial.md
  docs/visualize_clustered_contours.md
  mkdocs.yml
Labels: documentation

#541 Add indices aci ari
  docs/extract_index.md
  docs/img/tutorial_images/hyperspectral/aci_index.jpg
  docs/img/tutorial_images/hyperspectral/ari_index.jpg
  docs/img/tutorial_images/hyperspectral/gdvi.jpg
  plantcv/plantcv/apply_mask.py
  plantcv/plantcv/hyperspectral/extract_index.py
  tests/tests.py
Labels: enhancement, new feature

#544 fixed symbol causing error
  plantcv/plantcv/hyperspectral/extract_index.py
Labels: bugfix

#545 Add VIs to extract index updated version
  docs/extract_index.md
  docs/img/tutorial_images/hyperspectral/ndre_index.jpg
  docs/img/tutorial_images/hyperspectral/psnd_chla_index.jpg
  docs/img/tutorial_images/hyperspectral/psnd_chlb_index.jpg
  docs/img/tutorial_images/hyperspectral/wbi_index.jpg
  plantcv/plantcv/hyperspectral/analyze_index.py
  plantcv/plantcv/hyperspectral/extract_index.py
  plantcv/plantcv/transform/rescale.py
  tests/tests.py
Labels: documentation, enhancement, new feature

#548 Update sample_images to randomly sample image snapshots only
  plantcv/utils/sample_images.py
Labels: bugfix

#550 Add standard deviation filter
  docs/img/documentation_images/stdev_filter/cropped_plantago.jpg
  docs/img/documentation_images/stdev_filter/stdev_img11.jpg
  docs/img/documentation_images/stdev_filter/stdev_img111.jpg
  docs/img/documentation_images/stdev_filter/stdev_img45.jpg
  docs/stdev_filter.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/stdev_filter.py
  tests/tests.py
Labels: new feature

#551 stop copying the data, just reference it instead to save memory
  plantcv/plantcv/hyperspectral/extract_index.py
Labels: enhancement

#552 update param name from rgb_img to img
  docs/custom_range_threshold.md
  docs/nir_tutorial.md
  docs/updating.md
  plantcv/plantcv/threshold/threshold_methods.py
Labels: bugfix, documentation

#553 Visualize all available auto threshold methods
  docs/img/documentation_images/visualize_auto_threshold_methods/all_thresholds.jpg
  docs/visualize_auto_threshold_methods.md
  docs/visualize_clustered_contours.md
  mkdocs.yml
  plantcv/plantcv/visualize/__init__.py
  plantcv/plantcv/visualize/auto_threshold_methods.py
  tests/tests.py
Labels: enhancement, new feature

#554 fix links to screen shots in doc page
  docs/stdev_filter.md
Labels: bugfix
