Repository danforthcenter/plantcv, pull requests merged in 2020-01, with the labels that each got.

#505 Add threshold method for masking saturated pixels
  docs/img/documentation_images/saturation_threshold/saturation_threshold.jpg
  docs/img/documentation_images/saturation_threshold/vis_original_image.jpg
  docs/saturation_threshold.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/threshold/__init__.py
  plantcv/plantcv/threshold/threshold_methods.py
  tests/tests.py
Labels: enhancement, new feature

#504 Retain debug mode
  plantcv/plantcv/acute.py
  plantcv/plantcv/acute_vertex.py
  plantcv/plantcv/analyze_bound_horizontal.py
  plantcv/plantcv/analyze_bound_vertical.py
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/analyze_object.py
  plantcv/plantcv/analyze_thermal_values.py
  plantcv/plantcv/background_subtraction.py
  plantcv/plantcv/canny_edge_detect.py
  plantcv/plantcv/cluster_contour_splitimg.py
  plantcv/plantcv/cluster_contours.py
  plantcv/plantcv/crop.py
  plantcv/plantcv/crop_position_mask.py
  plantcv/plantcv/fill.py
  plantcv/plantcv/fluor_fvfm.py
  plantcv/plantcv/get_nir.py
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  plantcv/plantcv/hyperspectral/calibrate.py
  plantcv/plantcv/hyperspectral/extract_index.py
  plantcv/plantcv/hyperspectral/extract_wavelength.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/landmark_reference_pt_dist.py
  plantcv/plantcv/laplace_filter.py
  plantcv/plantcv/morphology/_iterative_prune.py
  plantcv/plantcv/morphology/check_cycles.py
  plantcv/plantcv/morphology/find_branch_pts.py
  plantcv/plantcv/morphology/find_tips.py
  plantcv/plantcv/morphology/prune.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_skeleton.py
  plantcv/plantcv/morphology/segment_sort.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  plantcv/plantcv/morphology/skeletonize.py
  plantcv/plantcv/naive_bayes_classifier.py
  plantcv/plantcv/object_composition.py
  plantcv/plantcv/rectangle_mask.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/roi_objects.py
  plantcv/plantcv/rotate.py
  plantcv/plantcv/scale_features.py
  plantcv/plantcv/shift_img.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/transform/color_correction.py
  plantcv/plantcv/transform/nonuniform_illumination.py
  plantcv/plantcv/transform/rescale.py
  plantcv/plantcv/visualize/clustered_contours.py
  plantcv/plantcv/visualize/colorize_masks.py
  plantcv/plantcv/visualize/histogram.py
  plantcv/plantcv/watershed.py
  plantcv/plantcv/within_frame.py
  plantcv/plantcv/y_axis_pseudolandmarks.py
Labels: enhancement

#516 analyze_spectral bugfix w print_results
  plantcv/plantcv/hyperspectral/analyze_spectral.py
Labels: bugfix

#517 Consistent debugging img filetype
  plantcv/plantcv/analyze_bound_horizontal.py
  plantcv/plantcv/analyze_bound_vertical.py
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/analyze_object.py
  plantcv/plantcv/cluster_contour_splitimg.py
  plantcv/plantcv/naive_bayes_classifier.py
  plantcv/plantcv/opening.py
  plantcv/plantcv/resize.py
Labels: enhancement

#519 Update analyze_spectral measurements
  docs/analyze_spectral.md
  plantcv/plantcv/hyperspectral/analyze_index.py
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  tests/tests.py
Labels: enhancement
