Repository danforthcenter/plantcv, pull requests merged in 2020-04, with the labels that each got.

#566 Add NIR summary stats
  docs/analyze_NIR_intensity.md
  plantcv/plantcv/analyze_nir_intensity.py
Labels: enhancement

#559 custom_range threshold in RGB
  plantcv/plantcv/threshold/threshold_methods.py
Labels: work in progress

#558 Update features for extract index
  docs/analyze_index.md
  docs/extract_index.md
  docs/extract_wavelength.md
  docs/hyperspectral_tutorial.md
  docs/img/tutorial_images/hyperspectral/aci_index.jpg
  docs/spectral_index.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/hyperspectral/__init__.py
  plantcv/plantcv/hyperspectral/extract_index.py
  plantcv/plantcv/spectral_index/__init__.py
  plantcv/plantcv/spectral_index/spectral_index.py
  tests/tests.py
Labels: bugfix, documentation, enhancement, new feature
