Repository danforthcenter/plantcv, pull requests merged in 2020-07, with the labels that each got.

#596 Updates to find_tips and find_branch_pts; Add analyze_stem function
  docs/analyze_stem.md
  docs/find_branch_pts.md
  docs/find_tips.md
  docs/img/documentation_images/analyze_stem/143_segmented_angles.jpg
  docs/img/documentation_images/analyze_stem/218_segmented_angles.jpg
  docs/output_measurements.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/morphology/__init__.py
  plantcv/plantcv/morphology/analyze_stem.py
  plantcv/plantcv/morphology/check_cycles.py
  plantcv/plantcv/morphology/find_branch_pts.py
  plantcv/plantcv/morphology/find_tips.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_path_length.py
  tests/tests.py
Labels: enhancement

#595 Adding option to segement_skeleton to generate random colors instead …
  docs/color_palette.md
  docs/params.md
  docs/updating.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/color_palette.py
  plantcv/plantcv/morphology/check_cycles.py
  plantcv/plantcv/morphology/segment_angle.py
  plantcv/plantcv/morphology/segment_combine.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_id.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_skeleton.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  tests/tests.py
Labels: enhancement, new feature

#598 Update CI/CD workflows
  .github/workflows/continuous-integration.yml
  .github/workflows/publish-package.yml
Labels: testing
