Repository danforthcenter/plantcv, pull requests merged in 2020-09, with the labels that each got.

#607 Config-based parallel processing
  docs/job_builder.md
  docs/metadata_parser.md
  docs/multiprocess.md
  docs/parallel_config.md
  docs/parallel_job_builder.md
  docs/parallel_metadata_parser.md
  docs/parallel_multiprocess.md
  docs/parallel_process_results.md
  docs/params.md
  docs/pipeline_parallel.md
  environment.yml
  mkdocs.yml
  plantcv-workflow.py
  plantcv/parallel/__init__.py
  plantcv/parallel/job_builder.py
  plantcv/parallel/multiprocess.py
  plantcv/parallel/parsers.py
  plantcv/plantcv/visualize/auto_threshold_methods.py
  requirements.txt
  tests/parallel_data/workflow_config_template.json
  tests/tests.py
Labels: new feature

#621 100% testing coverage
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/analyze_thermal_values.py
  plantcv/plantcv/hyperspectral/analyze_index.py
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  plantcv/plantcv/photosynthesis/analyze_fvfm.py
  plantcv/plantcv/print_image.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/transform/color_correction.py
  plantcv/plantcv/visualize/histogram.py
  tests/tests.py
Labels: testing

#622 Fix PlantCV release deployment workflow
  .github/workflows/publish-package.yml
Labels: bugfix

#623 Update deployment workflow to checkout all commits and tags
  .github/workflows/publish-package.yml
Labels: bugfix

#625 fix plotting bug when debug=None
  plantcv/plantcv/__init__.py
  plantcv/plantcv/plot_image.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/visualize/pseudocolor.py
Labels: bugfix
