Repository danforthcenter/plantcv, pull requests merged in 2020-05, with the labels that each got.

#576 Update read envi
  plantcv/plantcv/hyperspectral/read_data.py
  tests/hyperspectral_data/darkReference_darkReference.hdr
Labels: enhancement

#580 Update Dockerfile recipe to fix missing libGL dependency
  Dockerfile
Labels: bugfix

#578 Add chip size to find color card
  docs/transform_correct_color.md
  docs/updating.md
  plantcv/plantcv/transform/color_correction.py
  tests/tests.py
Labels: enhancement, new feature
