Repository danforthcenter/plantcv, pull requests merged in 2021-03, with the labels that each got.

#678 Add an attribute "include_all_subdirs" to WorkflowConfig
  docs/parallel_config.md
  plantcv/parallel/__init__.py
  plantcv/parallel/parsers.py
  tests/tests.py
Labels: enhancement

#684 Option to customize plot title in pcv.visualize.pseudocolor
  docs/updating.md
  docs/visualize_pseudocolor.md
  plantcv/plantcv/visualize/pseudocolor.py
  tests/tests.py
Labels: enhancement

#702 Update fill segments measurements
  docs/fill_segments.md
  plantcv/plantcv/morphology/fill_segments.py
  tests/tests.py
Labels: enhancement

#705 Add json datatype check in add observation
  docs/outputs.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/classes.py
  tests/tests.py
Labels: enhancement

#712 Create debug module
  docs/CONTRIBUTING.md
  plantcv/plantcv/_debug.py
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/analyze_object.py
  plantcv/plantcv/readimage.py
  tests/tests.py
Labels: enhancement

#722 Pcv.visualize.clustered contours optional bounding circles
  docs/multi-plant_tutorial.md
  docs/updating.md
  docs/visualize_clustered_contours.md
  plantcv/plantcv/visualize/clustered_contours.py
  tests/tests.py
Labels: enhancement, ready to review

#725 Cluster contours splitimg debug update
  plantcv/plantcv/cluster_contour_splitimg.py
  tests/tests.py
Labels: enhancement, ready to review

#730 Bug sample images subfolders
  plantcv/utils/sample_images.py
Labels: bugfix, ready to review

#735 Update _debug.py
  plantcv/plantcv/_debug.py
Labels: ready to review

#731 Add method to Outputs class to save results in multiple formats
  docs/Spectral_data.md
  docs/hyperspectral_tutorial.md
  docs/jupyter.md
  docs/morphology_tutorial.md
  docs/nir_tutorial.md
  docs/outputs.md
  docs/params.md
  docs/print_results.md
  docs/psII_tutorial.md
  docs/roi_multi.md
  docs/thermal_tutorial.md
  docs/updating.md
  docs/vis_nir_tutorial.md
  docs/vis_tutorial.md
  docs/watershed.md
  plantcv/plantcv/analyze_object.py
  plantcv/plantcv/classes.py
  plantcv/plantcv/print_results.py
  tests/data/data_results.csv
  tests/tests.py
Labels: new feature, ready to review

#726 add_deprecation_update_histogram_related
  docs/analyze_index.md
  docs/img/documentation_images/histogram/RGB_histogram.png
  docs/img/documentation_images/histogram/gray_histogram_bins.png
  docs/img/documentation_images/histogram/gray_histogram_default.png
  docs/img/documentation_images/histogram/gray_histogram_trimmed.png
  docs/nir_tutorial.md
  docs/updating.md
  docs/visualize_histogram.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/analyze_thermal_values.py
  plantcv/plantcv/deprecation_warning.py
  plantcv/plantcv/hyperspectral/analyze_index.py
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  plantcv/plantcv/spectral_index/spectral_index.py
  plantcv/plantcv/visualize/histogram.py
  tests/tests.py
Labels: documentation, enhancement, new feature, ready to review

#732 Add cmyk
  docs/img/documentation_images/rgb2cmyk/CMYK-black.jpg
  docs/img/documentation_images/rgb2cmyk/CMYK-cyan.jpg
  docs/img/documentation_images/rgb2cmyk/CMYK-magenta.jpg
  docs/img/documentation_images/rgb2cmyk/CMYK-yellow.jpg
  docs/img/documentation_images/rgb2cmyk/original_image.jpg
  docs/rgb2cmyk.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/rgb2gray_cmyk.py
  tests/tests.py
Labels: new feature, ready to review

#738 Option to turn off show warnings
  docs/params.md
  plantcv/plantcv/classes.py
  plantcv/plantcv/deprecation_warning.py
Labels: new feature, ready to review

#734 Add datatype check for overlay two imgs
  plantcv/plantcv/visualize/overlay_two_imgs.py
  tests/tests.py
Labels: enhancement, ready to review
