Repository danforthcenter/plantcv, pull requests merged in 2021-11, with the labels that each got.

#830 cast contour tuple as a list in find_objects
  plantcv/plantcv/find_objects.py
Labels: bugfix, ready to review

#829 Update color correction
  plantcv/plantcv/transform/color_correction.py
  tests/data/matrix_b1.npz
  tests/data/matrix_b2.npz
  tests/data/matrix_m1.npz
  tests/data/matrix_m2.npz
  tests/data/source1_matrix.npz
  tests/data/source2_matrix.npz
  tests/data/source_corrected.png
  tests/data/target_matrix.npz
  tests/data/transformation_matrix1.npz
Labels: bugfix, ready to review

#831 scale color correction matrices to 0-255 in quick color check
  plantcv/plantcv/transform/color_correction.py
Labels: ready to review

#832 Debug color correction
  plantcv/plantcv/transform/color_correction.py
  tests/data/matrix_m1.npz
  tests/data/matrix_m2.npz
  tests/data/source_corrected.png
  tests/data/transformation_matrix1.npz
Labels: ready to review

#833 Trigger GitHub Actions deployment workflow when a release is published
  .github/workflows/publish-package.yml
Labels: bugfix
