Repository danforthcenter/plantcv, pull requests merged in 2021-12, with the labels that each got.

#844 Use fewer contours in testing roi_objects
  tests/data/input_object_contours.npz
  tests/data/input_object_hierarchy.npz
  tests/data/input_roi_contour.npz
  tests/data/input_roi_hierarchy.npz
  tests/tests.py
Labels: testing, ready to review

#845 Update hyperspectral calibration function
  docs/calibrate.md
  plantcv/plantcv/hyperspectral/calibrate.py
  tests/tests.py
Labels: bugfix, ready to review

#846 Update dependency OpenCV to v4
  .github/workflows/continuous-integration.yml
  .github/workflows/publish-package.yml
  Dockerfile
  environment.yml
  plantcv/plantcv/roi/roi_methods.py
  requirements.txt
Labels: enhancement

#816 Annotation sub-package and point annotation tool (a.k.a. interactive CustomROI)
  docs/Points.md
  docs/img/documentation_images/annotate_Points/custom_roi.gif
  docs/img/documentation_images/annotate_Points/custom_roi.jpg
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/annotate/__init__.py
  plantcv/plantcv/annotate/points.py
  plantcv/plantcv/classes.py
  tests/tests.py
Labels: new feature, ready to review

#848 Finish refactor debugging
  plantcv/plantcv/cluster_contour_mask.py
  plantcv/plantcv/hyperspectral/extract_wavelength.py
  plantcv/plantcv/morphology/analyze_stem.py
  plantcv/plantcv/morphology/check_cycles.py
  plantcv/plantcv/morphology/find_branch_pts.py
  plantcv/plantcv/morphology/find_tips.py
  plantcv/plantcv/morphology/prune.py
  plantcv/plantcv/morphology/segment_angle.py
  plantcv/plantcv/morphology/segment_combine.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_id.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_path_length.py
  plantcv/plantcv/morphology/segment_skeleton.py
  plantcv/plantcv/morphology/segment_sort.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  plantcv/plantcv/morphology/skeletonize.py
  plantcv/plantcv/output_mask_ori_img.py
  plantcv/plantcv/spectral_index/spectral_index.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/transform/color_correction.py
  plantcv/plantcv/transform/nonuniform_illumination.py
  plantcv/plantcv/transform/rescale.py
  plantcv/plantcv/transform/resize.py
  plantcv/plantcv/transform/rotate.py
  plantcv/plantcv/visualize/clustered_contours.py
  plantcv/plantcv/visualize/colorspaces.py
  tests/tests.py
Labels: enhancement, ready to review
