Repository danforthcenter/plantcv, pull requests merged in 2021-06, with the labels that each got.

#757 Update morphology fill segments
  docs/fill_segments.md
  docs/morphology_tutorial.md
  docs/updating.md
  docs/visualize_colorize_label_img.md
  mkdocs.yml
  plantcv/plantcv/morphology/fill_segments.py
  plantcv/plantcv/visualize/__init__.py
  plantcv/plantcv/visualize/colorize_label_img.py
  tests/tests.py
Labels: enhancement, ready to review

#776 Debug update rgb2gray
  plantcv/plantcv/rgb2gray.py
  tests/tests.py
Labels: work in progress

#720 Update warp functions
  docs/img/documentation_images/transform_img_registration/overlay_after.png
  docs/img/documentation_images/transform_img_registration/overlay_before.png
  docs/img/documentation_images/transform_img_registration/ref_therm.png
  docs/img/documentation_images/transform_img_registration/tar_rgb.png
  docs/img/documentation_images/transform_warp/RGB_aligned.jpg
  docs/img/documentation_images/transform_warp/align_warp_overlay.png
  docs/img/documentation_images/transform_warp/align_warped.png
  docs/img/documentation_images/transform_warp/lmeds.png
  docs/img/documentation_images/transform_warp/mask.png
  docs/img/documentation_images/transform_warp/mask_overlay_nir.png
  docs/img/documentation_images/transform_warp/nir.png
  docs/img/documentation_images/transform_warp/overlayed_aligned.jpg
  docs/img/documentation_images/transform_warp/overlayed_orig.jpg
  docs/img/documentation_images/transform_warp/ref_pts.png
  docs/img/documentation_images/transform_warp/ref_tar.png
  docs/img/documentation_images/transform_warp/ref_tar_pts.png
  docs/img/documentation_images/transform_warp/ref_with_warpedoverlay.png
  docs/img/documentation_images/transform_warp/refimg.png
  docs/img/documentation_images/transform_warp/rgb.png
  docs/img/documentation_images/transform_warp/tar_pts.png
  docs/img/documentation_images/transform_warp/warp_overlay_no_ref.png
  docs/img/documentation_images/transform_warp/warped.png
  docs/img/documentation_images/transform_warp/warped_no_ref.png
  docs/transform_warp.md
  docs/updating.md
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/warp.py
  tests/tests.py
Labels: enhancement, ready to review

#739 add image_fusion to plantcv
  .github/workflows/continuous-integration.yml
  docs/image_fusion.md
  docs/img/documentation_images/image_fusion/NDVI.png
  docs/img/documentation_images/image_fusion/img1_rgb.png
  docs/img/documentation_images/image_fusion/img2_nir.png
  docs/img/documentation_images/image_fusion/mask.png
  docs/img/documentation_images/image_fusion/ndvi_colormap.png
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/image_fusion.py
  tests/tests.py
Labels: new feature, ready to review

#781 And support for BSQ data
  docs/read_image.md
  plantcv/plantcv/hyperspectral/read_data.py
  tests/hyperspectral_data/darkReference4
  tests/hyperspectral_data/darkReference4.hdr
  tests/tests.py
Labels: enhancement, ready to review

#789 Change line endings from CRLF to LF
  plantcv/plantcv/rgb2gray_cmyk.py
Labels: bugfix

#794 Update debug module fill
  plantcv/plantcv/fill.py
  tests/tests.py
Labels: ready to review

#777 Add a module "ecdf" (Empirical Cumulative Distribution Function) to "visualize" sub-package
  docs/img/documentation_images/histogram/RGB_histogram.png
  docs/img/documentation_images/histogram/gray_histogram_bins.png
  docs/img/documentation_images/histogram/gray_histogram_default.png
  docs/img/documentation_images/histogram/gray_histogram_trimmed.png
  docs/img/documentation_images/histogram/hist.jpg
  docs/img/documentation_images/visualize_obj_size_ecdf/ecdf_obj_size.png
  docs/img/documentation_images/visualize_obj_size_ecdf/mask.png
  docs/updating.md
  docs/visualize_histogram.md
  docs/visualize_obj_size_ecdf.md
  environment.yml
  mkdocs.yml
  plantcv/plantcv/visualize/__init__.py
  plantcv/plantcv/visualize/obj_size_ecdf.py
  requirements.txt
  tests/tests.py
Labels: documentation, new feature, ready to review

#791 Match multiple metadata values - simpler approach
  docs/parallel_config.md
  plantcv-workflow.py
  plantcv/parallel/parsers.py
  tests/tests.py
Labels: enhancement, ready to review
