Repository danforthcenter/plantcv, pull requests merged in 2021-09, with the labels that each got.

#807 Convert to _debug
  plantcv/plantcv/_debug.py
  plantcv/plantcv/acute_vertex.py
  plantcv/plantcv/analyze_bound_horizontal.py
  plantcv/plantcv/analyze_bound_vertical.py
  plantcv/plantcv/apply_mask.py
  plantcv/plantcv/auto_crop.py
  plantcv/plantcv/background_subtraction.py
  plantcv/plantcv/canny_edge_detect.py
  plantcv/plantcv/closing.py
  plantcv/plantcv/cluster_contours.py
  plantcv/plantcv/crop.py
  plantcv/plantcv/crop_position_mask.py
  plantcv/plantcv/dilate.py
  plantcv/plantcv/distance_transform.py
  plantcv/plantcv/erode.py
  plantcv/plantcv/fill.py
  plantcv/plantcv/fill_holes.py
  plantcv/plantcv/find_objects.py
  plantcv/plantcv/flip.py
  plantcv/plantcv/gaussian_blur.py
  plantcv/plantcv/hist_equalization.py
  plantcv/plantcv/image_add.py
  plantcv/plantcv/image_subtract.py
  plantcv/plantcv/invert.py
  plantcv/plantcv/laplace_filter.py
  plantcv/plantcv/logical_and.py
  plantcv/plantcv/logical_or.py
  plantcv/plantcv/logical_xor.py
  plantcv/plantcv/median_blur.py
  plantcv/plantcv/naive_bayes_classifier.py
  plantcv/plantcv/object_composition.py
  plantcv/plantcv/opening.py
  plantcv/plantcv/readbayer.py
  plantcv/plantcv/rectangle_mask.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/rgb2gray_hsv.py
  plantcv/plantcv/rgb2gray_lab.py
  plantcv/plantcv/roi/roi2mask.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/roi_objects.py
  plantcv/plantcv/scale_features.py
  plantcv/plantcv/scharr_filter.py
  plantcv/plantcv/shift_img.py
  plantcv/plantcv/sobel_filter.py
  plantcv/plantcv/spatial_clustering.py
  plantcv/plantcv/stdev_filter.py
  plantcv/plantcv/watershed.py
  plantcv/plantcv/white_balance.py
  plantcv/plantcv/x_axis_pseudolandmarks.py
  plantcv/plantcv/y_axis_pseudolandmarks.py
  tests/tests.py
Labels: Epic

#824 Synchronize the main branch with the 4x branch
  plantcv/plantcv/acute_vertex.py
  plantcv/plantcv/analyze_bound_horizontal.py
  plantcv/plantcv/analyze_bound_vertical.py
  plantcv/plantcv/apply_mask.py
  plantcv/plantcv/auto_crop.py
  plantcv/plantcv/background_subtraction.py
  plantcv/plantcv/canny_edge_detect.py
  plantcv/plantcv/closing.py
  plantcv/plantcv/cluster_contours.py
  plantcv/plantcv/crop.py
  plantcv/plantcv/crop_position_mask.py
  plantcv/plantcv/dilate.py
  plantcv/plantcv/distance_transform.py
  plantcv/plantcv/erode.py
  plantcv/plantcv/fill.py
  plantcv/plantcv/fill_holes.py
  plantcv/plantcv/find_objects.py
  plantcv/plantcv/flip.py
  plantcv/plantcv/gaussian_blur.py
  plantcv/plantcv/hist_equalization.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/image_add.py
  plantcv/plantcv/image_subtract.py
  plantcv/plantcv/invert.py
  plantcv/plantcv/laplace_filter.py
  plantcv/plantcv/logical_and.py
  plantcv/plantcv/logical_or.py
  plantcv/plantcv/logical_xor.py
  plantcv/plantcv/median_blur.py
  plantcv/plantcv/naive_bayes_classifier.py
  plantcv/plantcv/object_composition.py
  plantcv/plantcv/opening.py
  plantcv/plantcv/readbayer.py
  plantcv/plantcv/rectangle_mask.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/rgb2gray_hsv.py
  plantcv/plantcv/rgb2gray_lab.py
  plantcv/plantcv/roi/roi2mask.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/roi_objects.py
  plantcv/plantcv/scale_features.py
  plantcv/plantcv/scharr_filter.py
  plantcv/plantcv/shift_img.py
  plantcv/plantcv/sobel_filter.py
  plantcv/plantcv/spatial_clustering.py
  plantcv/plantcv/stdev_filter.py
  plantcv/plantcv/watershed.py
  plantcv/plantcv/white_balance.py
  plantcv/plantcv/x_axis_pseudolandmarks.py
  plantcv/plantcv/y_axis_pseudolandmarks.py
  tests/tests.py
Labels: ready to review

#690 Addition of constellation homologies workflow with tutorials
  docs/homology_acute.md
  docs/homology_constella.md
  docs/homology_constellaqc.md
  docs/homology_space.md
  docs/homology_starscape.md
  docs/img/documentation_images/homology_acute/B100_rep1_d10.jpg
  docs/img/documentation_images/homology_acute/acute_plms.png
  docs/img/documentation_images/homology_acute/mask.png
  docs/img/documentation_images/homology_constella/dendrogram.png
  docs/img/documentation_images/homology_starscape/prcomp_plot.png
  docs/img/documentation_images/homology_starscape/screeplot.png
  docs/tutorials.md
  docs/tutorials/homology_tutorial.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/acute.py
  plantcv/plantcv/homology/__init__.py
  plantcv/plantcv/homology/acute.py
  plantcv/plantcv/homology/constella.py
  plantcv/plantcv/homology/constellaqc.py
  plantcv/plantcv/homology/space.py
  plantcv/plantcv/homology/starscape.py
  tests/data/plms_annotated.csv
  tests/data/plms_df.csv
  tests/data/plms_landmarks.csv
  tests/data/plms_space_df.csv
  tests/data/plms_starscape_df.csv
  tests/tests.py
Labels: new feature, ready to review
