Repository danforthcenter/plantcv, pull requests merged in 2021-04, with the labels that each got.

#744 ignore spyder project files
  .gitignore
Labels: ready to review

#741 Fill segments debug update r
  plantcv/plantcv/morphology/fill_segments.py
  tests/tests.py
Labels: ready to review

#748 handle subdaily timestamps
  plantcv/parallel/parsers.py
  tests/parallel_data/images_w_date/NIR_SV_0_z1_h1_g0_e65_23_59_59.jpg
  tests/tests.py
Labels: bugfix, ready to review

#751 updated the PSII tutorial with segmentation recommendations
  docs/img/tutorial_images/psII/22_objcomp.jpg
  docs/img/tutorial_images/psII/27_fv_hist.jpg
  docs/img/tutorial_images/psII/36_pseudocolored.jpg
  docs/img/tutorial_images/psII/eroded_plant_mask.png
  docs/img/tutorial_images/psII/fdark.jpg
  docs/img/tutorial_images/psII/fdark2.png
  docs/img/tutorial_images/psII/filled_plant_mask.jpg
  docs/img/tutorial_images/psII/filled_plant_mask2.png
  docs/img/tutorial_images/psII/fmax.jpg
  docs/img/tutorial_images/psII/fmax2.png
  docs/img/tutorial_images/psII/fmax_rescaled.jpg
  docs/img/tutorial_images/psII/fmax_rescaled2.png
  docs/img/tutorial_images/psII/fmax_rescaled_sideways.jpg
  docs/img/tutorial_images/psII/fmin.jpg
  docs/img/tutorial_images/psII/fmin2.png
  docs/img/tutorial_images/psII/fvfm_hist2.png
  docs/img/tutorial_images/psII/id_obj.jpg
  docs/img/tutorial_images/psII/id_obj2.png
  docs/img/tutorial_images/psII/objcomp2.png
  docs/img/tutorial_images/psII/plant_mask.jpg
  docs/img/tutorial_images/psII/plant_mask2.png
  docs/img/tutorial_images/psII/pseudocolored.png
  docs/img/tutorial_images/psII/shapes.jpg
  docs/img/tutorial_images/psII/shapes2.png
  docs/psII_tutorial.md
Labels: documentation, ready to review

#569 pcv.visualize.pseudocolor and pcv.threshold.mask_bad
  docs/img/documentation_images/mask_bad_threshold/bad_mask_both.png
  docs/img/documentation_images/mask_bad_threshold/original_grayscale.jpg
  docs/img/documentation_images/pseudocolor/bad_mask.png
  docs/img/documentation_images/pseudocolor/pseudo_bad_marked.jpg
  docs/img/documentation_images/pseudocolor/pseudocolored_mask_bad.png
  docs/img/documentation_images/pseudocolor/pseudocolored_mask_bad_obj.png
  docs/mask_bad_threshold.md
  docs/visualize_pseudocolor.md
  mkdocs.yml
  plantcv/plantcv/threshold/__init__.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/visualize/pseudocolor.py
  tests/tests.py
Labels: documentation, enhancement, new feature, ready to review

#760 Update random sample method
  plantcv/utils/sample_images.py
Labels: enhancement, ready to review
