Repository danforthcenter/plantcv, pull requests merged in 2022-10, with the labels that each got.

#964 Add wavelength means Observation to analyze_spectral function
  docs/analyze_spectral.md
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  tests/plantcv/hyperspectral/test_analyze_spectral.py
Labels: bugfix, ready to review

#969 Update release 4.0
  docs/analyze_spectral.md
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  tests/plantcv/hyperspectral/test_analyze_spectral.py
Labels: ready to review, update

#970 Update 4.x
  docs/analyze_spectral.md
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  tests/plantcv/hyperspectral/test_analyze_spectral.py
Labels: ready to review, update

#937 Add parameters to mean adaptive thresh
  docs/gaussian_threshold.md
  docs/img/documentation_images/adaptive_threshold/pollen_grains.png
  docs/img/documentation_images/adaptive_threshold/pollen_grains_adaptive_Gauss_2000-15_scaled.png
  docs/img/documentation_images/adaptive_threshold/pollen_grains_adaptive_Gauss_25-5_scaled.png
  docs/img/documentation_images/adaptive_threshold/pollen_grains_adaptive_Gauss_250-15_scaled.png
  docs/img/documentation_images/adaptive_threshold/pollen_grains_adaptive_mean_15-5_scaled.png
  docs/img/documentation_images/adaptive_threshold/pollen_grains_adaptive_mean_2000-25_scaled.png
  docs/img/documentation_images/adaptive_threshold/pollen_grains_adaptive_mean_250-25_scaled.png
  docs/img/documentation_images/visualize_auto_threshold_methods/all_thresholds.jpg
  docs/mean_threshold.md
  docs/updating.md
  docs/visualize_auto_threshold_methods.md
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/visualize/auto_threshold_methods.py
  tests/plantcv/threshold/test_threshold_methods.py
  tests/plantcv/visualize/test_auto_threshold_methods.py
Labels: enhancement, ready to review

#972 Added compatibility for BIP data format of hsi images in read_image
  docs/read_image.md
  plantcv/plantcv/hyperspectral/read_data.py
  tests/testdata/darkReference4.hdr
Labels: enhancement, new feature
