Repository danforthcenter/plantcv, pull requests merged in 2022-07, with the labels that each got.

#916 Hsi filename pattern matching
  environment.yml
  plantcv/plantcv/hyperspectral/read_data.py
  requirements.txt
  tests/plantcv/hyperspectral/conftest.py
  tests/plantcv/hyperspectral/test_read_data.py
Labels: enhancement, ready to review

#919 Update 4x
  docs/apply_transformation_matrix.md
  docs/create_color_card_mask.md
  docs/find_color_card.md
  docs/get_color_matrix.md
  docs/load_matrix.md
  docs/mp_inverse.md
  docs/otsu_threshold.md
  docs/parallel_config.md
  docs/rgb2cmyk.md
  docs/save_matrix.md
  docs/texture_threshold.md
  docs/transform_correct_color.md
  docs/transform_resize.md
  docs/transformation_matrix.md
  docs/visualize_pseudocolor.md
  environment.yml
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/hyperspectral/write_data.py
  requirements.txt
  tests/plantcv/hyperspectral/conftest.py
  tests/plantcv/hyperspectral/test_read_data.py
  tests/plantcv/hyperspectral/test_write_data.py
Labels: ready to review, update

#887 Refactor parallel subpackage to use dataframes and grouping
  .github/workflows/continuous-integration.yml
  docs/jupyter.md
  docs/parallel_config.md
  docs/parallel_job_builder.md
  docs/parallel_metadata_parser.md
  docs/parallel_process_results.md
  docs/parallel_workflow_inputs.md
  docs/pipeline_parallel.md
  docs/tools.md
  environment.yml
  mkdocs.yml
  plantcv-utils.py
  plantcv-workflow.py
  plantcv/parallel/__init__.py
  plantcv/parallel/job_builder.py
  plantcv/parallel/multiprocess.py
  plantcv/parallel/parsers.py
  plantcv/parallel/process_results.py
  plantcv/parallel/workflow_inputs.py
  plantcv/utils/converters.py
  tests/parallel/conftest.py
  tests/parallel/test_job_builder.py
  tests/parallel/test_multiprocess.py
  tests/parallel/test_parsers.py
  tests/parallel/test_workflow_inputs.py
  tests/testdata/phenodata_dir/metadata.json
  tests/testdata/plantcv-script.py
  tests/testdata/workflowconfig_template.json
  tests/utils/test_json2csv.py
Labels: new feature, ready to review, update

#911 Added automatic grid detection to multi
  docs/objects.md
  docs/roi_auto_grid.md
  docs/roi_multi.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/classes.py
  plantcv/plantcv/roi/__init__.py
  plantcv/plantcv/roi/roi_methods.py
  tests/plantcv/roi/conftest.py
  tests/plantcv/roi/test_roi.py
  tests/plantcv/test_Objects.py
  tests/plantcv/test_segment_image_series.py
Labels: enhancement, ready to review, update

#925 Update sample_images to handle phenodata datasets
  plantcv/utils/sample_images.py
  tests/testdata/phenodata_dir/2015-04-07/snapshot808/NIR_SV_0_z2500_h2_g0_e65_4859_0.png
  tests/testdata/phenodata_dir/2015-04-07/snapshot808/NIR_SV_90_z2500_h2_g0_e65_4860_0.png
  tests/testdata/phenodata_dir/2015-04-07/snapshot808/NIR_TV_z2500_h2_g0_e65_4863_0.png
  tests/testdata/phenodata_dir/2015-04-07/snapshot808/VIS_SV_0_z2500_h2_g0_e82_4854_0.png
  tests/testdata/phenodata_dir/2015-04-07/snapshot808/VIS_SV_90_z2500_h2_g0_e82_4855_0.png
  tests/testdata/phenodata_dir/2015-04-07/snapshot808/VIS_TV_z2500_h2_g0_e110_4858_0.png
  tests/testdata/phenodata_dir/2015-05-21/snapshot131596/NIR_SV_0_z1_h1_g0_e65_259887_0.png
  tests/testdata/phenodata_dir/2015-05-21/snapshot131596/NIR_SV_90_z1_h1_g0_e65_259888_0.png
  tests/testdata/phenodata_dir/2015-05-21/snapshot131596/NIR_TV_z1_h1_g0_e65_259891_0.png
  tests/testdata/phenodata_dir/2015-05-21/snapshot131596/VIS_SV_0_z1_h1_g0_e82_259882_0.png
  tests/testdata/phenodata_dir/2015-05-21/snapshot131596/VIS_SV_90_z1_h1_g0_e82_259883_0.png
  tests/testdata/phenodata_dir/2015-05-21/snapshot131596/VIS_TV_z1_h1_g0_e110_259886_0.png
  tests/utils/conftest.py
  tests/utils/test_sample_images.py
Labels: bugfix
