Repository danforthcenter/plantcv, pull requests merged in 2022-01, with the labels that each got.

#823 Two io functions
  docs/io_random_subset.md
  docs/io_read_dataset.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/io/__init__.py
  plantcv/plantcv/io/random_subset.py
  plantcv/plantcv/io/read_dataset.py
  tests/tests.py
Labels: new feature, ready to review

#856 add line return to Sample Images function
  plantcv/utils/sample_images.py
Labels: bugfix

#858 Add deepsource.io config file to repository
  .deepsource.toml
Labels: testing, ready to review

#810 Pixel scatter visualization
  docs/img/documentation_images/visualize_pixel_scatter_vis/10.9.1.31_pos-153-001-004_2019-10-31-13-05_1.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/10.9.1.31_pos-153-001-004_2019-10-31-13-05_2.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/10.9.1.31_pos-153-001-004_2019-10-31-13-05_3.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/10.9.1.31_pos-153-001-004_2019-10-31-13-05_4.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/VIS_TV_z500_h2_g0_e100_163042_0_m.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/VIS_TV_z500_h2_g0_e100_163174_0_m.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/VIS_TV_z500_h2_g0_e100_163228_0_m.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/VIS_TV_z500_h2_g0_e100_167692_0_m.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/brassica_pixel_scatter_Gb.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/brassica_pixel_scatter_ba.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/pixel_scatter_G.png
  docs/img/documentation_images/visualize_pixel_scatter_vis/pixel_scatter_s.png
  docs/updating.md
  docs/visualize_pixel_scatter_vis.md
  mkdocs.yml
  plantcv/plantcv/io/read_dataset.py
  plantcv/plantcv/visualize/__init__.py
  plantcv/plantcv/visualize/pixel_scatter_vis.py
  tests/plantcv/visualize/test_pixel_scatter_plot.py
Labels: new feature, ready to review

#840 2D threshold
  docs/img/documentation_images/threshold_2channels/VIS_TV_z500_h2_g0_e100_163042_0_ba_mask_inv_m.png
  docs/img/documentation_images/threshold_2channels/VIS_TV_z500_h2_g0_e100_163042_0_ba_mask_m.png
  docs/img/documentation_images/threshold_2channels/VIS_TV_z500_h2_g0_e100_163042_0_m.png
  docs/threshold_dual_channels.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/threshold/__init__.py
  plantcv/plantcv/threshold/threshold_methods.py
  tests/plantcv/threshold/test_threshold_methods.py
Labels: new feature, ready to review

#861 Replace symlinks with image files
  docs/img/documentation_images/background_subtraction/TEST_BACKGROUND.jpg
  docs/img/documentation_images/background_subtraction/TEST_FOREGROUND.jpg
Labels: documentation, bugfix, ready to review
