Repository danforthcenter/plantcv, pull requests merged in 2022-09, with the labels that each got.

#941 Update code conduct
  README.md
  docs/CODE_OF_CONDUCT.md
Labels: documentation, ready to review, update

#942 Enable actions release4
  .github/workflows/continuous-integration.yml
Labels: testing, ready to review

#939 Add helper function to centralize usage of OpenCV findContours
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/analyze_bound_horizontal.py
  plantcv/plantcv/analyze_bound_vertical.py
  plantcv/plantcv/analyze_object.py
  plantcv/plantcv/crop_position_mask.py
  plantcv/plantcv/find_objects.py
  plantcv/plantcv/morphology/_iterative_prune.py
  plantcv/plantcv/morphology/check_cycles.py
  plantcv/plantcv/morphology/find_branch_pts.py
  plantcv/plantcv/morphology/find_tips.py
  plantcv/plantcv/morphology/prune.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_skeleton.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  plantcv/plantcv/rectangle_mask.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/roi_objects.py
  plantcv/plantcv/visualize/obj_size_ecdf.py
Labels: ready to review, update

#946 Update roi rectangle objects class
  docs/roi_rectangle.md
  docs/updating.md
  plantcv/plantcv/roi/roi_methods.py
  tests/plantcv/roi/test_roi.py
Labels: enhancement, ready to review, update, Objects class implementation

#951 Update roi.ellipse to use objects class
  docs/roi_ellipse.md
  docs/updating.md
  plantcv/plantcv/roi/roi_methods.py
  tests/plantcv/roi/test_roi.py
Labels: enhancement, ready to review, Objects class implementation

#947 Update find objects objects class
  docs/find_objects.md
  docs/updating.md
  plantcv/plantcv/find_objects.py
  tests/plantcv/test_find_objects.py
Labels: enhancement, ready to review, update, Objects class implementation

#931 standard color correction matrix function
  docs/std_color_matrix.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/color_correction.py
  tests/plantcv/transform/test_color_correction.py
Labels: new feature, ready to review

#959 Pin matplotlib to < 3.6
  environment.yml
  requirements.txt
Labels: bugfix, ready to review

#957 Fix test cache dir
  environment.yml
  requirements.txt
  tests/plantcv/test_segment_image_series.py
Labels: bugfix, ready to review

#960 Pin matplotlib version
  environment.yml
  requirements.txt
Labels: ready to review, update

#952 use objects class in roi2mask
  docs/roi2mask.md
  docs/updating.md
  plantcv/plantcv/roi/roi2mask.py
  tests/plantcv/roi/test_roi2mask.py
Labels: ready to review, update, Objects class implementation

#958 Reconfigure dask futures and client management
  plantcv/parallel/multiprocess.py
  tests/parallel/test_multiprocess.py
Labels: ready to review, update
