Repository danforthcenter/plantcv, pull requests merged in 2022-06, with the labels that each got.

#890 fix bug in dtype_dict in hyperspectral read_data
  plantcv/plantcv/hyperspectral/read_data.py
Labels: bug, ready to review

#888 Hyperspectral rotation
  docs/hyperspectral_rot90.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/hyperspectral/__init__.py
  plantcv/plantcv/hyperspectral/rot90.py
  tests/plantcv/hyperspectral/test_rot90.py
Labels: new feature, ready to review

#899 add default values
  docs/params.md
Labels: documentation

#901 Fix overindented docstrings
  plantcv/plantcv/crop.py
  plantcv/plantcv/hyperspectral/_avg_reflectance.py
  plantcv/plantcv/hyperspectral/_inverse_covariance.py
  plantcv/plantcv/hyperspectral/extract_wavelength.py
  plantcv/plantcv/morphology/_iterative_prune.py
  plantcv/plantcv/morphology/analyze_stem.py
  plantcv/plantcv/morphology/check_cycles.py
  plantcv/plantcv/morphology/find_branch_pts.py
  plantcv/plantcv/morphology/find_tips.py
  plantcv/plantcv/morphology/prune.py
  plantcv/plantcv/morphology/segment_angle.py
  plantcv/plantcv/morphology/segment_combine.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_id.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_path_length.py
  plantcv/plantcv/morphology/segment_skeleton.py
  plantcv/plantcv/morphology/segment_sort.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  plantcv/plantcv/transform/nonuniform_illumination.py
  plantcv/plantcv/transform/rescale.py
  plantcv/plantcv/visualize/colorize_masks.py
  plantcv/plantcv/visualize/colorspaces.py
  plantcv/plantcv/visualize/histogram.py
  plantcv/plantcv/visualize/overlay_two_imgs.py
Labels: ready to review, cleanup

#908 Update 4x
  .github/PULL_REQUEST_TEMPLATE.md
  docs/params.md
  docs/pr_review_process.md
  mkdocs.yml
  plantcv/learn/naive_bayes.py
  plantcv/plantcv/analyze_color.py
  plantcv/plantcv/analyze_thermal_values.py
  plantcv/plantcv/crop.py
  plantcv/plantcv/hyperspectral/_avg_reflectance.py
  plantcv/plantcv/hyperspectral/_inverse_covariance.py
  plantcv/plantcv/hyperspectral/analyze_index.py
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  plantcv/plantcv/hyperspectral/extract_wavelength.py
  plantcv/plantcv/morphology/_iterative_prune.py
  plantcv/plantcv/morphology/analyze_stem.py
  plantcv/plantcv/morphology/check_cycles.py
  plantcv/plantcv/morphology/find_branch_pts.py
  plantcv/plantcv/morphology/find_tips.py
  plantcv/plantcv/morphology/prune.py
  plantcv/plantcv/morphology/segment_angle.py
  plantcv/plantcv/morphology/segment_combine.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_id.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_path_length.py
  plantcv/plantcv/morphology/segment_skeleton.py
  plantcv/plantcv/morphology/segment_sort.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  plantcv/plantcv/morphology/skeletonize.py
  plantcv/plantcv/plot_image.py
  plantcv/plantcv/roi/roi2mask.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/transform/nonuniform_illumination.py
  plantcv/plantcv/transform/rescale.py
  plantcv/plantcv/visualize/colorize_masks.py
  plantcv/plantcv/visualize/colorspaces.py
  plantcv/plantcv/visualize/histogram.py
  plantcv/plantcv/visualize/hyper_histogram.py
  plantcv/plantcv/visualize/overlay_two_imgs.py
  setup.py
Labels: ready to review, update

#889 Write hyperspectral data
  docs/updating.md
  docs/write_data.md
  mkdocs.yml
  plantcv/plantcv/hyperspectral/__init__.py
  plantcv/plantcv/hyperspectral/write_data.py
  tests/plantcv/hyperspectral/test_write_data.py
Labels: new feature, ready to review

#910 Doc updates
  docs/apply_transformation_matrix.md
  docs/create_color_card_mask.md
  docs/find_color_card.md
  docs/get_color_matrix.md
  docs/load_matrix.md
  docs/mp_inverse.md
  docs/otsu_threshold.md
  docs/parallel_config.md
  docs/rgb2cmyk.md
  docs/save_matrix.md
  docs/texture_threshold.md
  docs/transform_correct_color.md
  docs/transform_resize.md
  docs/transformation_matrix.md
  docs/visualize_pseudocolor.md
Labels: documentation, ready to review
