Repository danforthcenter/plantcv, pull requests merged in 2022-04, with the labels that each got.

#882 added sample column to case without variables
  plantcv/utils/converters.py
Labels: bugfix, ready to review

#884 Update 4x
  plantcv/utils/converters.py
Labels: ready to review, update

#885 support for other dtypes in color correction
  plantcv/plantcv/transform/color_correction.py
Labels: enhancement, ready to review
