Repository danforthcenter/plantcv, pull requests merged in 2022-08, with the labels that each got.

#929 replace list expression with explicit for loop in segment_image_series
  plantcv/plantcv/segment_image_series.py
Labels: ready to review, cleanup

#935 Add gif to gitattributes to treat as binary
  .gitattributes
Labels: bugfix, ready to review

#936 Apply bugfix to v4
  .gitattributes
Labels: ready to review, update
