Repository danforthcenter/plantcv, pull requests merged in 2023-03, with the labels that each got.

#998 Fix ImportError in plantcv caused by change in skimage.feature function name
  .github/workflows/continuous-integration.yml
  .github/workflows/publish-package.yml
  environment.yml
  plantcv/plantcv/closing.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/watershed.py
  requirements.txt
Labels: bugfix

#1004 Update release 4.0
  .github/workflows/continuous-integration.yml
  .github/workflows/publish-package.yml
  docs/installation.md
  docs/read_image.md
  docs/segment_combine.md
  environment.yml
  plantcv/plantcv/closing.py
  plantcv/plantcv/fill.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/morphology/segment_combine.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/watershed.py
  requirements.txt
  tests/plantcv/morphology/test_segment_combine.py
  tests/testdata/darkReference4.hdr
Labels: update

#1012 Changed print to plot in analyze_shape.md
  docs/analyze_shape.md
Labels: documentation

#1017 Change print to plot in analyze color
  docs/analyze_color.md
Labels: documentation

#1005 Update 4.x
  .github/workflows/continuous-integration.yml
  .github/workflows/publish-package.yml
  docs/installation.md
  docs/read_image.md
  docs/segment_combine.md
  environment.yml
  plantcv/plantcv/closing.py
  plantcv/plantcv/fill.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/morphology/segment_combine.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/watershed.py
  requirements.txt
  tests/plantcv/morphology/test_segment_combine.py
  tests/testdata/darkReference4.hdr
Labels: bugfix, update

#980 Utilize Objects class in pcv.roi.from_binary_image
  docs/roi_from_binary_image.md
  docs/updating.md
  plantcv/plantcv/roi/roi_methods.py
  tests/plantcv/roi/test_roi.py
Labels: enhancement, ready to review, Objects class implementation

#1010 Update save_matrix.md to remove quotations surrounding filename
  docs/save_matrix.md
Labels: documentation, ready to review, update

#1011 Typo fix to mask in thermal_hist
  docs/analyze_thermal_values.md
Labels: documentation

#1014 Fixed typo in visualize_colorspace.md
  docs/visualize_colorspace.md
Labels: documentation

#1015 test PR, changed python versions listed for testing
  docs/installation.md
Labels: documentation

#1016 Update visualize_ovelay_two_imgs.md
  docs/visualize_ovelay_two_imgs.md
Labels: documentation

#1022 Update PULL_REQUEST_TEMPLATE.md changed PR template link from stable branch to latest branch.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#1034 changed white balance print to plot
  docs/white_balance.md
Labels: documentation

#1035 Update_print to plot_gaussian_threshold.md
  docs/flip.md
Labels: documentation

#1038 Update HistEqualization
  docs/HistEqualization.md
Labels: documentation

#1041 Update canny_edge_detect.md
  docs/canny_edge_detect.md
Labels: documentation

#1044 Update_image_add_print to plot
  docs/image_add.md
Labels: documentation

#1068 make Objects class return Objects instance while iterating
  plantcv/plantcv/classes.py
  plantcv/plantcv/roi/roi2mask.py
  tests/plantcv/test_Objects.py
Labels: ready to review, update, Objects class implementation

#1045 update print to plot in triangle_threshold
  docs/triangle_threshold.md
Labels: documentation

#1046 changed print to plot in check_cycles
  docs/check_cycles.md
Labels: documentation

#1047 change print to plot transform rescale
  docs/transform_rescale.md
Labels: documentation

#1048 Update_image_subtract
  docs/image_subtract.md
Labels: documentation

#1088 Update_naive_bayes_classifier
  docs/naive_bayes_classifier.md
Labels: documentation

#1087 Updated print to plot in find_objects
  docs/find_objects.md
Labels: documentation

#1086 updated print to plot in get_nir
  docs/get_nir.md
Labels: documentation

#1085 Update_median_blur
  docs/median_blur.md
Labels: documentation

#1083 Update_Mean_Threshold
  docs/mean_threshold.md
Labels: documentation

#1077 update print to plot in invert
  docs/invert.md
Labels: documentation

#1073 change print to plot stdev_filter.md
  docs/stdev_filter.md
Labels: documentation

#1067 Update_logical_or_print to plot
  docs/logical_or.md
Labels: documentation

#1065 changed print to plot in roi_multi
  docs/roi_multi.md
Labels: documentation

#1064 changed print to plot in roi_from_binary_image
  docs/roi_from_binary_image.md
Labels: documentation

#1059 changed print to plot in spectral_index
  docs/spectral_index.md
Labels: documentation

#1057 change print to plot in roi_circle
  docs/roi_circle.md
Labels: documentation

#1053 Update_landmark_reference_pt_dist
  docs/landmark_reference_pt_dist.md
Labels: documentation

#1050 Change print to plot to sobel_filter
  docs/sobel_filter.md
Labels: documentation

#1093 Update release 4.0
  docs/visualize_ovelay_two_imgs.md
Labels: ready to review

#1094 Changed print to plot in extract_wavelength.md
  docs/extract_wavelength.md
Labels: ready to review
