Repository danforthcenter/plantcv, pull requests merged in 2023-08, with the labels that each got.

#1316 Update seed tutorial URLs
  docs/tutorials.md
  docs/tutorials/seed_analysis_tutorial.md
Labels: documentation, update

#1320 update contribution guide
  docs/CONTRIBUTING.md
Labels: documentation, ready to review

#1324 Revise updating.md
  docs/updating.md
Labels: ready to review, update

#1318 Only add tabulate naive bayes.md [skip ci]
  docs/tools.md
Labels: documentation, ready to review

#1325 Rename to ksize in adaptive thresholding methods
  docs/gaussian_threshold.md
  docs/mean_threshold.md
  docs/updating.md
  plantcv/plantcv/threshold/threshold_methods.py
  tests/plantcv/threshold/test_threshold_methods.py
Labels: ready to review, update

#1326 Add extra table of contents links
  mkdocs.yml
Labels: documentation, ready to review

#1327 Deprecate print results
  docs/analyze_stem.md
  docs/find_branch_pts.md
  docs/find_tips.md
  docs/print_results.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/print_results.py
  tests/plantcv/test_print_results.py
Labels: ready to review, update

#1329 smf gallery wall
  docs/tutorials.md
  docs/tutorials/hyperspectral_smf_tutorial.md
Labels: documentation, ready to review

#1333 Rename job_extra to job_extra_directives
  docs/parallel_config.md
  docs/pipeline_parallel.md
  plantcv/parallel/__init__.py
  tests/testdata/workflowconfig_template.json
Labels: ready to review, update

#1332 Update installation guide
  docs/installation.md
Labels: documentation, ready to review

#1334 Change license mpl2
  LICENSE
Labels: ready to review, update

#1336 Update PSII tutorial
  docs/tutorials.md
  docs/tutorials/psII_tutorial.md
Labels: documentation, ready to review

#1335 Update json2csv outputs
  docs/pipeline_parallel.md
  docs/tools.md
  plantcv/utils/cli.py
  plantcv/utils/converters.py
  tests/utils/test_cli.py
  tests/utils/test_json2csv.py
Labels: enhancement, ready to review, update

#1338 Tutorial arabidopsis multi plant
  docs/tutorials.md
  docs/tutorials/arabidopsis_multi_plant_tutorial.md
Labels: documentation, ready to review

#1340 Set num_labels to num ROIs
  plantcv/plantcv/create_labels.py
Labels: bugfix

#1341 Remove find objects functions
  docs/analysis_approach.md
  docs/find_objects.md
  docs/img/documentation_images/find_objects/contours.jpg
  docs/img/documentation_images/find_objects/mask.jpg
  docs/img/documentation_images/find_objects/original_image.jpg
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/find_objects.py
  tests/plantcv/test_find_objects.py
Labels: ready to review, update

#1350 Collapse hierarchical headers for CSV files
  plantcv/utils/converters.py
Labels: bugfix, ready to review

#1347 Bump upper version of NumPy
  environment.yml
  plantcv/plantcv/analyze/npq.py
  plantcv/plantcv/visualize/chlorophyll_fluorescence.py
  requirements.txt
  tests/plantcv/homology/test_acute.py
  tests/plantcv/transform/test_color_correction.py
Labels: ready to review, update

#1353 Update matplotlib supported versions
  environment.yml
  plantcv/plantcv/classes.py
  requirements.txt
Labels: ready to review, update
