Repository danforthcenter/plantcv, pull requests merged in 2023-06, with the labels that each got.

#1161 start function bound horizontal
  docs/analyze_bound_horizontal2.md
  docs/analyze_bound_vertical2.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/analyze/__init__.py
  plantcv/plantcv/analyze/bound_horizontal.py
  plantcv/plantcv/analyze/bound_vertical.py
  plantcv/plantcv/analyze/color.py
  plantcv/plantcv/analyze/size.py
  tests/plantcv/analyze/test_bound_horizontal.py
  tests/plantcv/analyze/test_bound_vertical.py
Labels: new feature, ready to review

#1175 Define type for markers in watershed
  plantcv/plantcv/morphology/fill_segments.py
  plantcv/plantcv/segment_image_series.py
Labels: bugfix, ready to review

#1176 Update release4
  plantcv/plantcv/morphology/fill_segments.py
  plantcv/plantcv/segment_image_series.py
Labels: ready to review, update

#1172 Iterate analyze grayscale
  docs/analyze_grayscale.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/analyze/__init__.py
  plantcv/plantcv/analyze/grayscale.py
  tests/plantcv/analyze/test_grayscale.py
Labels: new feature, ready to review

#1177 Add updated analysis function for thermal images that utilizes iteration
  docs/analyze_thermal.md
  docs/img/documentation_images/analyze_thermal_values/temp_hist.png
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/analyze/__init__.py
  plantcv/plantcv/analyze/color.py
  plantcv/plantcv/analyze/thermal.py
  tests/plantcv/analyze/test_thermal.py
Labels: new feature, ready to review

#1181 Add type to markers
  plantcv/plantcv/morphology/fill_segments.py
Labels: bugfix, ready to review

#1183 Update release 4.0
  .github/workflows/continuous-integration.yml
Labels: ready to review, update

#1178 Add analyze.spectral_reflectance function
  docs/analyze_spectral_reflectance.md
  docs/img/documentation_images/analyze_spectral_reflectance/spectral_plot.png
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/analyze/__init__.py
  plantcv/plantcv/analyze/spectral_reflectance.py
  tests/plantcv/analyze/test_spectral_reflectance.py
Labels: new feature, ready to review

#1182 Update 4x
  .github/workflows/continuous-integration.yml
Labels: ready to review, update

#1186 Remove obj from homology.acute
  docs/homology_acute.md
  docs/updating.md
  plantcv/plantcv/homology/acute.py
  tests/plantcv/homology/test_acute.py
Labels: ready to review, update

#1169 Update x axis pseudolandmarks, remove `obj` input parameter
  docs/updating.md
  docs/x_axis_pseudolandmarks.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/homology/__init__.py
  plantcv/plantcv/homology/x_axis_pseudolandmark.py
  tests/plantcv/homology/test_x_axis_pseudolandmarks.py
  tests/plantcv/test_x_axis_pseudolandmarks.py
Labels: enhancement, ready to review, update, Objects class implementation

#1185 Update y axis pseudolandmarks
  docs/updating.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/homology/__init__.py
  plantcv/plantcv/homology/y_axis_pseudolandmarks.py
  tests/plantcv/homology/test_y_axis_pseudolandmarks.py
  tests/plantcv/test_y_axis_pseudolandmarks.py
Labels: enhancement, ready to review

#995 Updates to stored "tips" and "branch_pts" getting stored to observations during Morphology workflows
  plantcv/plantcv/morphology/segment_sort.py
Labels: enhancement, new feature, morphology-subpackage, ready to review

#1198 Skip CSV output for x-y points
  plantcv/utils/converters.py
Labels: bugfix

#1192 auto_crop replace objects param with mask
  docs/auto_crop.md
  docs/updating.md
  plantcv/plantcv/auto_crop.py
  tests/plantcv/test_auto_crop.py
Labels: ready to review, update

#1199 Move landmark_reference_pt_dist to the homology submodule
  docs/homology_landmark_reference_pt_dist.md
  docs/homology_x_axis_pseudolandmarks.md
  docs/homology_y_axis_pseudolandmarks.md
  docs/output_measurements.md
  docs/params.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/homology/__init__.py
  plantcv/plantcv/homology/landmark_reference_pt_dist.py
  tests/plantcv/homology/test_landmark_reference_pt_dist.py
Labels: ready to review, update

#1200 Refactor scale_features
  docs/homology_scale_features.md
  docs/params.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/homology/__init__.py
  plantcv/plantcv/homology/scale_features.py
  tests/plantcv/homology/test_scale_features.py
Labels: new feature, ready to review, update

#1195 Deprecate cluster_contours
  docs/cluster_contours.md
  docs/img/documentation_images/cluster_contour/13_roi_mask.jpg
  docs/img/documentation_images/cluster_contour/14_clusters.jpg
  docs/img/documentation_images/cluster_contour/show_grid.jpg
  docs/params.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/cluster_contours.py
  tests/plantcv/test_cluster_contours.py
Labels: ready to review

#1196 Deprecate cluster contours splitimg
  docs/cluster_contours_splitimg.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/cluster_contour_splitimg.py
  tests/plantcv/test_cluster_contour_splitimg.py
Labels: ready to review, cleanup

#1197 Deprecate cluster contours mask
  plantcv/plantcv/__init__.py
  plantcv/plantcv/cluster_contour_mask.py
Labels: ready to review, update

#1187 Deprecate acute_vertex
  docs/acute_vertex.md
  docs/img/documentation_images/acute_vertex/av_example_image.jpg
  docs/img/documentation_images/acute_vertex/av_output.jpg
  docs/output_measurements.md
  docs/params.md
  docs/updating.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/acute_vertex.py
  tests/plantcv/test_acute_vertex.py
Labels: ready to review, update

#1188 Deprecate analyze bound horizontal
  docs/analysis_approach.md
  docs/analyze_bound_horizontal.md
  docs/output_measurements.md
  docs/outputs.md
  docs/params.md
  docs/print_results.md
  docs/updating.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/analyze_bound_horizontal.py
  tests/plantcv/test_analyze_bound_horizontal.py
Labels: ready to review, update

#1189 Deprecate analyze bound vertical
  docs/analysis_approach.md
  docs/analyze_bound_vertical.md
  docs/output_measurements.md
  docs/outputs.md
  docs/params.md
  docs/print_results.md
  docs/updating.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/analyze_bound_vertical.py
  tests/plantcv/test_analyze_bound_vertical.py
Labels: ready to review, update

#1190 Deprecate analyze color
  docs/analysis_approach.md
  docs/analyze_color.md
  docs/output_measurements.md
  docs/outputs.md
  docs/print_image.md
  docs/print_results.md
  docs/updating.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/analyze_color.py
  tests/plantcv/test_analyze_color.py
Labels: work in progress, update

#1204 Minor docs fixes
  docs/output_measurements.md
  mkdocs.yml
Labels: documentation, ready to review

#1205 Deprecate analyze_nir_intensity
  docs/analysis_approach.md
  docs/analyze_NIR_intensity.md
  docs/analyze_grayscale.md
  docs/img/documentation_images/analyze_grayscale/nir_histogram.jpg
  docs/img/documentation_images/analyze_grayscale/original_image.jpg
  docs/img/documentation_images/analyze_grayscale/pseudocolored_image.jpg
  docs/img/documentation_images/analyze_grayscale/shapes.jpg
  docs/outputs.md
  docs/print_image.md
  docs/print_results.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/analyze_nir_intensity.py
  tests/plantcv/test_analyze_nir_intensity.py
Labels: ready to review, update

#1206 Deprecate analyze_object
  docs/analysis_approach.md
  docs/analyze_shape.md
  docs/analyze_size.md
  docs/analyze_stem.md
  docs/img/documentation_images/analyze_size/objects_on_image.jpg
  docs/img/documentation_images/analyze_size/original_image.jpg
  docs/img/documentation_images/analyze_size/shapes_on_image.jpg
  docs/output_measurements.md
  docs/outputs.md
  docs/params.md
  docs/print_results.md
  docs/roi_auto_grid.md
  docs/roi_multi.md
  docs/updating.md
  plantcv/plantcv/__init__.py
  plantcv/plantcv/analyze_object.py
  tests/plantcv/test_analyze_object.py
Labels: ready to review, update

#1208 Remove hyperspectral.analyze_index
  docs/analysis_approach.md
  docs/analyze_index.md
  docs/outputs.md
  docs/print_results.md
  docs/tutorials/hyperspectral_tutorial.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/hyperspectral/__init__.py
  plantcv/plantcv/hyperspectral/analyze_index.py
  tests/plantcv/hyperspectral/test_analyze_index.py
Labels: ready to review, update

#1209 Deprecate rectangle mask
  docs/img/documentation_images/rectangle_mask/grayscale_image.jpg
  docs/img/documentation_images/rectangle_mask/masked.jpg
  docs/img/documentation_images/rectangle_mask/roi.jpg
  docs/rectangle_mask.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/rectangle_mask.py
  tests/plantcv/test_rectangle_mask.py
Labels: ready to review, update

#1201 Iterate psii analysis
  docs/analysis_approach.md
  docs/analyze_npq.md
  docs/analyze_yii.md
  docs/img/documentation_images/analyze_npq/npq_histogram.png
  docs/img/documentation_images/analyze_yii/dark_fluor_induction.png
  docs/img/documentation_images/analyze_yii/fqfm_colormap.png
  docs/img/documentation_images/analyze_yii/fqfm_histogram.png
  docs/img/documentation_images/analyze_yii/fvfm_colormap.png
  docs/img/documentation_images/analyze_yii/fvfm_histogram.png
  docs/img/documentation_images/analyze_yii/fvfm_images.jpg
  docs/img/documentation_images/analyze_yii/light_fluor_induction.png
  docs/img/documentation_images/fluor_fvfm/fqfm_histogram.png
  docs/img/documentation_images/fluor_fvfm/fvfm_histogram.png
  docs/img/documentation_images/photosynthesis_reassign_frame_labels/da_induction.png
  docs/img/documentation_images/photosynthesis_reassign_frame_labels/la_induction.png
  docs/img/documentation_images/visualize_chlorophyll_fluorescence/induction_curve.png
  docs/img/documentation_images/visualize_chlorophyll_fluorescence/leaf_labels.png
  docs/img/tutorial_images/psII/ari_hist.png
  docs/img/tutorial_images/psII/ci_hist.png
  docs/img/tutorial_images/psII/dark_chl_curve.png
  docs/img/tutorial_images/psII/light_chl_curve.png
  docs/img/tutorial_images/psII/ndvi_hist.png
  docs/output_measurements.md
  docs/photosynthesis_reassign_frame_labels.md
  docs/print_image.md
  docs/tutorials/psII_tutorial.md
  docs/updating.md
  docs/visualize_chlorophyll_fluorescence.md
  environment.yml
  mkdocs.yml
  plantcv/plantcv/analyze/__init__.py
  plantcv/plantcv/analyze/npq.py
  plantcv/plantcv/analyze/yii.py
  plantcv/plantcv/photosynthesis/__init__.py
  plantcv/plantcv/photosynthesis/analyze_npq.py
  plantcv/plantcv/photosynthesis/analyze_yii.py
  plantcv/plantcv/photosynthesis/reassign_frame_labels.py
  plantcv/plantcv/plot_image.py
  plantcv/plantcv/print_image.py
  plantcv/plantcv/visualize/__init__.py
  plantcv/plantcv/visualize/chlorophyll_fluorescence.py
  requirements.txt
  tests/conftest.py
  tests/plantcv/analyze/test_npq.py
  tests/plantcv/analyze/test_yii.py
  tests/plantcv/photosynthesis/test_analyze_npq.py
  tests/plantcv/photosynthesis/test_reassign_frame_labels.py
  tests/plantcv/visualize/test_chlorophyll_fluorescence.py
Labels: new feature, ready to review

#1210 remove max_val param from threshold.binary()
  docs/binary_threshold.md
  docs/updating.md
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/threshold/threshold_methods.py
  tests/plantcv/threshold/test_threshold_methods.py
Labels: ready to review
