Repository danforthcenter/plantcv, pull requests merged in 2023-10, with the labels that each got.

#1361 Enable multi label input
  docs/analyze_bound_horizontal2.md
  docs/analyze_bound_vertical2.md
  docs/analyze_color2.md
  docs/analyze_grayscale.md
  docs/analyze_npq.md
  docs/analyze_size.md
  docs/analyze_spectral_index.md
  docs/analyze_spectral_reflectance.md
  docs/analyze_thermal.md
  docs/analyze_yii.md
  docs/outputs.md
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/analyze/npq.py
  plantcv/plantcv/analyze/yii.py
  tests/plantcv/analyze/test_bound_horizontal.py
  tests/plantcv/analyze/test_bound_vertical.py
  tests/plantcv/analyze/test_color.py
  tests/plantcv/analyze/test_grayscale.py
  tests/plantcv/analyze/test_npq.py
  tests/plantcv/analyze/test_size.py
  tests/plantcv/analyze/test_spectral_index.py
  tests/plantcv/analyze/test_spectral_reflectance.py
  tests/plantcv/analyze/test_thermal.py
  tests/plantcv/analyze/test_yii.py
  tests/plantcv/test_helper_iterate_analysis.py
Labels: enhancement

#1364 1363 floodfill function
  docs/floodfill.md
  docs/img/documentation_images/floodfill/Figure1.png
  docs/img/documentation_images/floodfill/floodfill-Figure2.png
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/floodfill.py
  tests/conftest.py
  tests/plantcv/test_floodfill.py
  tests/testdata/floodfill.png
Labels: new feature, ready to review

#1372 Documentation minor bug fixes
  docs/read_image.md
  docs/roi2mask.md
  docs/updating.md
  plantcv/plantcv/floodfill.py
Labels: documentation, bugfix, ready to review

#1374 Update spectral wavelengths for CropReporter datasets
  docs/photosynthesis_read_cropreporter.md
  plantcv/plantcv/photosynthesis/read_cropreporter.py
Labels: bugfix, ready to review
