Repository danforthcenter/plantcv, pull requests merged in 2023-07, with the labels that each got.

#1212 remove max_val param from threshold.mean()
  docs/mean_threshold.md
  docs/updating.md
  plantcv/plantcv/threshold/threshold_methods.py
  tests/plantcv/threshold/test_threshold_methods.py
Labels: ready to review

#1213 remove max_val param from threshold.otsu()
  docs/otsu_threshold.md
  docs/updating.md
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/visualize/auto_threshold_methods.py
  tests/plantcv/threshold/test_threshold_methods.py
Labels: ready to review

#1218 remove max_val param from threshold.triangle()
  docs/triangle_threshold.md
  docs/updating.md
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/visualize/auto_threshold_methods.py
  tests/plantcv/threshold/test_threshold_methods.py
Labels: ready to review

#1220 remove max_val param from threshold._call_threshold()
  plantcv/plantcv/threshold/threshold_methods.py
Labels: ready to review

#1221 remove max_val param from threshold._call_adaptive_threshold()
  plantcv/plantcv/threshold/threshold_methods.py
Labels: ready to review

#1222 Remove deprecated plantcv.rotate function
  docs/hyperspectral_rot90.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/rotate.py
  tests/plantcv/test_rotate.py
Labels: ready to review

#1224 remove max_val param from threshold.dual_channels()
  docs/threshold_dual_channels.md
  docs/updating.md
  plantcv/plantcv/threshold/threshold_methods.py
  tests/plantcv/threshold/test_threshold_methods.py
Labels: ready to review

#1215 Add all-contributors table and badge
  README.md
Labels: enhancement, documentation, ready to review

#1216 Deprecate object composition
  docs/analysis_approach.md
  docs/homology_y_axis_pseudolandmarks.md
  docs/object_composition.md
  docs/params.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/object_composition.py
  plantcv/plantcv/report_size_marker_area.py
  tests/plantcv/test_object_composition.py
Labels: ready to review, update

#1223 optimizing naive_bayes_classifier
  plantcv/plantcv/naive_bayes_classifier.py
Labels: ready to review

#1226 Add config file for Read the Docs
  .readthedocs.yaml
Labels: documentation, ready to review

#1230 Update release-4.0 from main
  .readthedocs.yaml
  README.md
  docs/find_color_card.md
  plantcv/plantcv/morphology/segment_sort.py
Labels: ready to review, update

#1228 Deprecate roi objects
  docs/analysis_approach.md
  docs/img/documentation_images/roi_objects/kept_objects1.jpg
  docs/img/documentation_images/roi_objects/kept_objects2.jpg
  docs/img/documentation_images/roi_objects/mask1.jpg
  docs/img/documentation_images/roi_objects/mask2.jpg
  docs/img/documentation_images/roi_objects/obj_on_img1.jpg
  docs/img/documentation_images/roi_objects/obj_on_img2.jpg
  docs/params.md
  docs/roi_custom.md
  docs/roi_objects.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/roi_objects.py
  tests/plantcv/test_roi_objects.py
Labels: ready to review, update, Objects class implementation

#1294 Deprecate get_nir
  docs/get_nir.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/get_nir.py
  tests/plantcv/test_get_nir.py
Labels: ready to review

#1295 Deprecate analyze spectral
  docs/analysis_approach.md
  docs/analyze_spectral.md
  docs/tutorials/hyperspectral_tutorial.md
  mkdocs.yml
  plantcv/plantcv/hyperspectral/__init__.py
  plantcv/plantcv/hyperspectral/analyze_spectral.py
  tests/plantcv/hyperspectral/test_analyze_spectral.py
  tests/plantcv/test_deprecation_warning.py
Labels: ready to review

#1298 Update Watershed tutorial
  docs/tutorials.md
  docs/tutorials/watershed_segmentation_tutorial.md
Labels: documentation, ready to review

#1300 Add grayscale tutorial and replace old NIR
  docs/tutorials.md
  docs/tutorials/grayscale_tutorial.md
  docs/tutorials/nir_tutorial.md
Labels: documentation, ready to review

#1309 Update PSII dataset names
  docs/analyze_npq.md
  docs/analyze_yii.md
  docs/photosynthesis_read_cropreporter.md
  docs/photosynthesis_reassign_frame_labels.md
  docs/tutorials/psII_tutorial.md
  docs/visualize_chlorophyll_fluorescence.md
  environment.yml
  plantcv/plantcv/analyze/npq.py
  plantcv/plantcv/analyze/yii.py
  plantcv/plantcv/classes.py
  plantcv/plantcv/photosynthesis/read_cropreporter.py
  plantcv/plantcv/photosynthesis/reassign_frame_labels.py
  plantcv/plantcv/visualize/chlorophyll_fluorescence.py
  requirements.txt
  tests/conftest.py
  tests/plantcv/analyze/test_npq.py
  tests/plantcv/analyze/test_yii.py
  tests/plantcv/photosynthesis/conftest.py
  tests/plantcv/photosynthesis/test_psii_data.py
  tests/plantcv/photosynthesis/test_read_cropreporter.py
  tests/plantcv/photosynthesis/test_reassign_frame_labels.py
  tests/plantcv/test_plot_image.py
  tests/plantcv/test_print_image.py
  tests/plantcv/test_show_dataarray.py
  tests/plantcv/visualize/test_chlorophyll_fluorescence.py
Labels: ready to review, update

#1301 Tutorial update vis nir
  docs/tutorials.md
  docs/tutorials/vis_nir_tutorial.md
Labels: documentation, ready to review

#1302 Tutorial Update thermal
  docs/analyze_thermal.md
  docs/tutorials.md
  docs/tutorials/thermal_tutorial.md
Labels: documentation, ready to review

#1303 Update vis tutorial
  docs/tutorials.md
  docs/tutorials/vis_tutorial.md
Labels: documentation, ready to review

#1305 Update multi object tutorial
  docs/analysis_approach.md
  docs/analyze_grayscale.md
  docs/analyze_size.md
  docs/apply_mask.md
  docs/background_subtraction.md
  docs/binary_threshold.md
  docs/custom_range_threshold.md
  docs/dilate.md
  docs/erode.md
  docs/image_add.md
  docs/image_subtract.md
  docs/index.md
  docs/invert.md
  docs/jupyter.md
  docs/laplace_filter.md
  docs/logical_or.md
  docs/median_blur.md
  docs/roi_filter.md
  docs/sobel_filter.md
  docs/tutorials.md
  docs/tutorials/multi-plant_tutorial.md
  docs/visualize_histogram.md
Labels: documentation, ready to review

#1306 Update ml / Naive Bayes tutorial
  docs/tutorials.md
  docs/tutorials/machine_learning_tutorial.md
Labels: documentation, ready to review

#1308 Update morphology_tutorial
  docs/tutorials.md
  docs/tutorials/morphology_tutorial.md
Labels: documentation, ready to review

#1311 Update tutorial input output
  docs/tutorials.md
  docs/tutorials/input_output_tutorial.md
Labels: documentation, ready to review

#1314 Remove max value references
  docs/tutorials/hyperspectral_tutorial.md
  docs/tutorials/psII_tutorial.md
  docs/within_frame.md
Labels: documentation, ready to review, update
