Repository danforthcenter/plantcv, pull requests merged in 2023-04, with the labels that each got.

#956 Hsi read data flexible hdr format
  docs/Spectral_data.md
  docs/read_image.md
  docs/spectral_index.md
  docs/tutorials/hyperspectral_tutorial.md
  plantcv/plantcv/hyperspectral/__init__.py
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/readimage.py
  tests/plantcv/hyperspectral/conftest.py
  tests/plantcv/hyperspectral/test_read_data.py
  tests/testdata/arcgis.hdr
  tests/testdata/darkReference_arcgis
  tests/testdata/darkReference_arcgis.hdr
Labels: enhancement, ready to review, update, cleanup

#1104 Update 4x
  docs/Spectral_data.md
  docs/extract_wavelength.md
  docs/gaussian_threshold.md
  docs/logical_xor.md
  docs/nonuniform_illumination.md
  docs/object_composition.md
  docs/otsu_threshold.md
  docs/output_mask.md
  docs/read_image.md
  docs/spectral_index.md
  docs/tutorials/hyperspectral_tutorial.md
  environment.yml
  plantcv/plantcv/hyperspectral/read_data.py
  plantcv/plantcv/readimage.py
  requirements.txt
  tests/plantcv/hyperspectral/conftest.py
  tests/plantcv/hyperspectral/test_read_data.py
  tests/testdata/arcgis.hdr
  tests/testdata/darkReference_arcgis
  tests/testdata/darkReference_arcgis.hdr
Labels: ready to review, update

#1099 Replace command-line scripts with console scripts
  MANIFEST.in
  docs/jupyter.md
  docs/naive_bayes.md
  docs/naive_bayes_classifier.md
  docs/naive_bayes_multiclass.md
  docs/output_measurements.md
  docs/parallel_config.md
  docs/parallel_workflow_inputs.md
  docs/pipeline_parallel.md
  docs/roi_multi.md
  docs/tools.md
  plantcv/learn/cli.py
  plantcv/parallel/cli.py
  plantcv/utils/cli.py
  setup.py
  tests/learn/test_cli.py
  tests/parallel/test_cli.py
  tests/utils/test_cli.py
Labels: enhancement, bugfix, ready to review

#954 Rename objects parameter in pcv.auto_crop
  docs/auto_crop.md
  docs/updating.md
  plantcv/plantcv/auto_crop.py
  tests/plantcv/test_auto_crop.py
Labels: enhancement, ready to review, update, Objects class implementation

#1037 update roi_objects with Objects class
  docs/roi_objects.md
  docs/updating.md
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/roi_objects.py
  tests/plantcv/test_roi_objects.py
Labels: ready to review, Objects class implementation

#1139 Update 4x with updates in main
  docs/opening.md
  docs/photosynthesis_read_cropreporter.md
  docs/read_bayer.md
  docs/read_image.md
  docs/rectangle_mask.md
  docs/report_size_marker.md
  docs/rgb2cmyk.md
  docs/rgb2gray.md
  docs/rgb2hsv.md
  docs/rgb2lab.md
  docs/roi2mask.md
  docs/roi_objects.md
  docs/roi_rectangle.md
  docs/rotate2.md
  docs/saturation_threshold.md
  docs/scale_features.md
  docs/scharr_filter.md
  docs/segment_angle.md
  docs/segment_curvature.md
  docs/segment_euclidean_length.md
  docs/segment_id.md
  docs/segment_insertion_angle.md
  docs/segment_pathlength.md
  docs/segment_skeleton.md
  docs/segment_sort.md
  docs/segment_tangent_angle.md
  docs/shift.md
Labels: ready to review, update

#1141 Simplify histogram code and fix bug in minimum value calculation
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/visualize/histogram.py
Labels: bugfix, ready to review

#1142 Update 4.x
  plantcv/plantcv/analyze_nir_intensity.py
  plantcv/plantcv/visualize/histogram.py
Labels: ready to review, update

#1144 Fix threshold dual channels returning bad dtype
  plantcv/plantcv/threshold/threshold_methods.py
Labels: bugfix, ready to review
