Repository danforthcenter/plantcv, pull requests merged in 2023-05, with the labels that each got.

#1147 Make helper roi_filter function
  docs/img/documentation_images/roi_filter/bin_img.png
  docs/img/documentation_images/roi_filter/mask_cutto.png
  docs/img/documentation_images/roi_filter/mask_partial.png
  docs/img/documentation_images/roi_filter/rgb_img.png
  docs/img/documentation_images/roi_filter/roi_img.png
  docs/roi_filter.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/roi/__init__.py
  plantcv/plantcv/roi/roi_methods.py
  tests/plantcv/roi/test_roi.py
Labels: ready to review, update, Objects class implementation

#1148 Add iteration helper function
  plantcv/plantcv/_helpers.py
  tests/plantcv/test_helper_iterate_analysis.py
Labels: new feature, ready to review

#1152 Add composition helper function
  plantcv/plantcv/_helpers.py
  tests/plantcv/test_helper_object_composition.py
Labels: new feature, work in progress

#1153 Add grayscale to rgb helper
  plantcv/plantcv/_helpers.py
  tests/plantcv/test_helper_grayscale_to_rgb.py
Labels: new feature, ready to review

#1150 Add affine color correction function
  docs/img/documentation_images/transform_affine_color_corr/tobacco_leaves.jpg
  docs/img/documentation_images/transform_affine_color_corr/tobacco_leaves_corrected.jpg
  docs/std_color_matrix.md
  docs/transform_affine_color_correction.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/color_correction.py
  tests/plantcv/transform/test_color_correction.py
Labels: new feature, ready to review

#1157 Update release 4
  docs/img/documentation_images/transform_affine_color_corr/tobacco_leaves.jpg
  docs/img/documentation_images/transform_affine_color_corr/tobacco_leaves_corrected.jpg
  docs/transform_affine_color_correction.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/color_correction.py
  tests/plantcv/transform/test_color_correction.py
Labels: ready to review, update

#1154 Add analysis submodule and shape analysis function
  docs/analyze_size.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/analyze/__init__.py
  plantcv/plantcv/analyze/size.py
  tests/plantcv/analyze/test_objects.py
Labels: new feature, ready to review

#1159 Added-warn-function-replace-print
  plantcv/plantcv/background_subtraction.py
Labels: ready to review, update

#1160 Add warn cluster contour splitimg
  plantcv/plantcv/cluster_contour_splitimg.py
Labels: ready to review, update

#1163 Add-warn-replace-print-obj-comp
  plantcv/plantcv/object_composition.py
Labels: ready to review, update

#1164 add-warn-replace-print-roi_objects
  plantcv/plantcv/roi_objects.py
Labels: ready to review, update

#1165 add-warn-replace-print-analyze_index
  plantcv/plantcv/hyperspectral/analyze_index.py
  tests/plantcv/hyperspectral/test_analyze_index.py
Labels: ready to review, update

#1166 add-warn-replace-print-roi_methods
  plantcv/plantcv/roi/roi_methods.py
  tests/plantcv/roi/test_roi.py
Labels: ready to review, update

#1167 add-warn-replace-print-threshold_methods
  plantcv/plantcv/threshold/threshold_methods.py
Labels: ready to review, update

#1168 add-warn-replace-print-helpers
  plantcv/plantcv/_helpers.py
Labels: ready to review, update

#1170 Add analyze color function to analyze submodule
  .github/workflows/continuous-integration.yml
  .github/workflows/publish-package.yml
  docs/analyze_color2.md
  docs/img/documentation_images/analyze_color/hue_histograms.png
  docs/img/documentation_images/analyze_color/original_multi.jpg
  docs/updating.md
  environment.yml
  mkdocs.yml
  plantcv/plantcv/analyze/__init__.py
  plantcv/plantcv/analyze/color.py
  plantcv/plantcv/classes.py
  plantcv/plantcv/plot_image.py
  plantcv/plantcv/print_image.py
  requirements.txt
  tests/plantcv/analyze/test_color.py
  tests/plantcv/analyze/test_size.py
  tests/plantcv/test_print_image.py
Labels: enhancement, ready to review
