Repository danforthcenter/plantcv, pull requests merged in 2023-11, with the labels that each got.

#1386 Update README.md with Deepsource badge
  README.md
Labels: documentation, new feature, ready to review

#1362 add new function called detect_color_card
  docs/find_color_card.md
  docs/img/documentation_images/correct_color_imgs/detect_color_card.png
  docs/transform_correct_color.md
  docs/transform_detect_color_card.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/color_correction.py
  plantcv/plantcv/transform/detect_color_card.py
  plantcv/plantcv/transform/find_color_card.py
  tests/plantcv/transform/test_color_correction.py
  tests/plantcv/transform/test_detect_color_card.py
  tests/plantcv/transform/test_find_color_card.py
Labels: enhancement, new feature, ready to review, update

#1376 Roi coord dtype cast
  plantcv/plantcv/roi/roi_methods.py
Labels: bugfix, ready to review

#1402 too many leading '#' for block comment
  plantcv/plantcv/annotate/points.py
Labels: ready to review, cleanup

#1392 Removed whitespace surrounding docstring text
  plantcv/plantcv/annotate/points.py
  plantcv/plantcv/classes.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  plantcv/plantcv/segment_image_series.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/visualize/auto_threshold_methods.py
  plantcv/plantcv/visualize/pixel_scatter_vis.py
Labels: ready to review, cleanup

#1399 Whitespace after ","
  plantcv/plantcv/visualize/pixel_scatter_vis.py
Labels: ready to review, cleanup

#1408 PTC-W0019 - Consider using literal syntax
  plantcv/plantcv/image_fusion.py
  plantcv/plantcv/photosynthesis/read_cropreporter.py
Labels: ready to review, cleanup

#1391 changing doc string conventions for deepsource best practices
  plantcv/plantcv/classes.py
  plantcv/plantcv/hyperspectral/write_data.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/segment_image_series.py
  plantcv/plantcv/threshold/threshold_methods.py
Labels: ready to review, cleanup

#1393 FLK-D200
  plantcv/learn/cli.py
  plantcv/utils/cli.py
Labels: cleanup

#1398 changing max linewidth in file
  plantcv/plantcv/morphology/__init__.py
Labels: ready to review, cleanup

#1401 changes for deepsource expecting 2 blank lines
  plantcv/plantcv/hyperspectral/write_data.py
Labels: ready to review, cleanup

#1404 Deleted variable mask=mask
  plantcv/plantcv/threshold/threshold_methods.py
Labels: cleanup

#1394 changed comparison order per deepsource standards
  plantcv/plantcv/homology/acute.py
Labels: ready to review, cleanup

#1397 added line after docstring
  plantcv/plantcv/classes.py
Labels: ready to review, cleanup

#1405 Replaced obs with _
  plantcv/plantcv/analyze/npq.py
  plantcv/plantcv/threshold/threshold_methods.py
Labels: ready to review, cleanup

#1407 Removing unused libraries
  plantcv/plantcv/__init__.py
  plantcv/plantcv/homology/starscape.py
  plantcv/plantcv/hyperspectral/write_data.py
  tests/plantcv/hyperspectral/test_write_data.py
  tests/plantcv/test_deprecation_warning.py
Labels: ready to review, cleanup

#1390 Update colorspaces.py add CMYK
  docs/img/documentation_images/visualize_colorspaces/all_colorspaces.jpg
  plantcv/plantcv/rgb2gray_cmyk.py
  plantcv/plantcv/visualize/colorspaces.py
  tests/plantcv/visualize/test_colorspaces.py
Labels: enhancement, ready to review, update

#1395 PYL-W0612 deepsource replace unused vars
  plantcv/learn/naive_bayes.py
  plantcv/parallel/__init__.py
  plantcv/parallel/job_builder.py
  plantcv/parallel/parsers.py
  plantcv/parallel/process_results.py
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/analyze/bound_horizontal.py
  plantcv/plantcv/analyze/bound_vertical.py
  plantcv/plantcv/analyze/grayscale.py
  plantcv/plantcv/analyze/size.py
  plantcv/plantcv/analyze/spectral_index.py
  plantcv/plantcv/create_labels.py
  plantcv/plantcv/crop_position_mask.py
  plantcv/plantcv/homology/scale_features.py
  plantcv/plantcv/homology/x_axis_pseudolandmark.py
  plantcv/plantcv/io/read_dataset.py
  plantcv/plantcv/morphology/_iterative_prune.py
  plantcv/plantcv/morphology/analyze_stem.py
  plantcv/plantcv/morphology/prune.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_path_length.py
  plantcv/plantcv/morphology/segment_skeleton.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/transform/color_correction.py
  plantcv/plantcv/visualize/pixel_scatter_vis.py
  tests/plantcv/test_create_labels.py
Labels: ready to review, cleanup

#1411 Remove old utility scripts
  utils/README.md
  utils/util-append-file-image-name.py
  utils/util-avg_background_img.py
  utils/util-downsize-images.py
  utils/util-prepare_bayes_class_columns.R
Labels: ready to review, cleanup
