Repository danforthcenter/plantcv, pull requests merged in 2024-08, with the labels that each got.

#1580 Add geospatial attributes to spectral_data class
  docs/Spectral_data.md
  plantcv/plantcv/classes.py
Labels: ready to review, update

#1574 Add quality control for image color
  docs/img/documentation_images/qc_exposure/quality_control_bad.png
  docs/img/documentation_images/qc_exposure/quality_control_good.png
  docs/qc_exposure.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/qc/__init__.py
  plantcv/plantcv/qc/exposure.py
  tests/plantcv/qc/__init__.py
  tests/plantcv/qc/test_exposure.py
Labels: new feature, ready to review

#1571 Add kmeans cli
  docs/kmeans_classifier.md
  docs/tools.md
  plantcv/learn/cli.py
  tests/learn/test_cli.py
Labels: enhancement, ready to review

#1576 Add "Quick Cutto" ROI function
  plantcv/plantcv/roi/quick_filter.py
  tests/plantcv/roi/test_quick_filter.py
Labels: enhancement, ready to review

#1578 1575 image tiling
  docs/img/documentation_images/visualize_tile/Tile_1.jpg
  docs/img/documentation_images/visualize_tile/Tile_2.jpg
  docs/img/documentation_images/visualize_tile/Tile_3.jpg
  docs/img/documentation_images/visualize_tile/Tile_4.jpg
  docs/img/documentation_images/visualize_tile/Tile_output.jpg
  docs/updating.md
  docs/visualize_tile.md
  mkdocs.yml
  plantcv/plantcv/visualize/__init__.py
  plantcv/plantcv/visualize/tile.py
  tests/plantcv/visualize/conftest.py
  tests/plantcv/visualize/test_tile.py
Labels: new feature, ready to review
