Repository danforthcenter/plantcv, pull requests merged in 2024-02, with the labels that each got.

#1441 Randomize color order default for pcv.watershed()
  plantcv/plantcv/watershed.py
Labels: enhancement, update

#1442 Change None values to none strings
  plantcv/utils/converters.py
Labels: bugfix, ready to review

#1439 fix-PYL-C0209
  plantcv/learn/cli.py
  plantcv/plantcv/_version.py
  plantcv/plantcv/io/read_dataset.py
  plantcv/plantcv/morphology/segment_angle.py
  plantcv/plantcv/morphology/segment_combine.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_id.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_path_length.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/visualize/hyper_histogram.py
  plantcv/plantcv/visualize/obj_sizes.py
  plantcv/plantcv/visualize/pseudocolor.py
  plantcv/utils/converters.py
Labels: ready to review, cleanup

#1449 Add min_size to `detect_color_card` kwargs
  docs/transform_detect_color_card.md
  plantcv/plantcv/transform/detect_color_card.py
Labels: enhancement, ready to review

#1451 visualize.colorspaces.py bugfix
  plantcv/plantcv/visualize/colorspaces.py
Labels: bugfix

#1447 Deepsource fix remove extra line return in init file
  plantcv/plantcv/visualize/__init__.py
Labels: ready to review, cleanup

#1446 1436 merging function
  docs/img/documentation_images/transform_merge_images/vert_tree_1.jpg
  docs/img/documentation_images/transform_merge_images/vert_tree_2.jpg
  docs/img/documentation_images/transform_merge_images/vert_tree_3.jpg
  docs/img/documentation_images/transform_merge_images/vert_tree_merged.jpg
  docs/transform_merge_images.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/merge_images.py
  tests/plantcv/transform/conftest.py
  tests/plantcv/transform/test_merge_images.py
  tests/testdata/merged_HA.jpg
  tests/testdata/merged_HG.jpg
  tests/testdata/merged_HS.jpg
  tests/testdata/merged_VA.jpg
  tests/testdata/merged_VG.jpg
  tests/testdata/merged_VS.jpg
  tests/testdata/mergehoriz/horiz_1.jpg
  tests/testdata/mergehoriz/horiz_2.jpg
  tests/testdata/mergehoriz/horiz_3.jpg
  tests/testdata/mergevert/vert_1.jpg
  tests/testdata/mergevert/vert_2.jpg
  tests/testdata/mergevert/vert_3.jpg
Labels: new feature, ready to review

#1462 Update codecov action
  .deepsource.toml
  .github/workflows/continuous-integration.yml
  README.md
  tests/plantcv/test_plot_image.py
Labels: bugfix, ready to review

#1430 Add pcv.filters.eccentricity
  docs/filters_eccentricity.md
  docs/img/documentation_images/filters_eccentricity/count_img.jpg
  docs/img/documentation_images/filters_eccentricity/count_mask.png
  docs/img/documentation_images/filters_eccentricity/discs_mask_scaled.png
  docs/img/documentation_images/filters_eccentricity/discs_pre_scaled.png
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/__init__.py
  plantcv/plantcv/filters/__init__.py
  plantcv/plantcv/filters/eccentricity.py
  tests/plantcv/filters/conftest.py
  tests/plantcv/filters/test_eccentricity.py
Labels: new feature, ready to review
