Repository danforthcenter/plantcv, pull requests merged in 2024-11, with the labels that each got.

#1621 Obj size ecdf docs bugfix
  docs/updating.md
  docs/visualize_obj_size_ecdf.md
Labels: documentation

#1570 Kmeans grayscale
  docs/kmeans_classifier.md
  docs/train_kmeans.md
  plantcv/learn/train_kmeans.py
  plantcv/plantcv/kmeans_classifier.py
  tests/conftest.py
  tests/learn/conftest.py
  tests/learn/test_kmeans_train.py
  tests/plantcv/test_kmeans_classifier.py
  tests/testdata/kmeans_classifier_dir/combo_mask_example.png
  tests/testdata/kmeans_classifier_dir/kmeans_out.fit
  tests/testdata/kmeans_classifier_dir/label_example_0.png
  tests/testdata/kmeans_classifier_dir/label_example_1.png
  tests/testdata/kmeans_classifier_dir/label_example_2.png
  tests/testdata/kmeans_classifier_dir/label_example_3.png
  tests/testdata/kmeans_classifier_dir/labeled_image.png
  tests/testdata/kmeans_classifier_gray_dir/combo_mask_example_gray.png
  tests/testdata/kmeans_classifier_gray_dir/kmeans_out_gray.fit
  tests/testdata/kmeans_classifier_gray_dir/label_example_gray_0.png
  tests/testdata/kmeans_classifier_gray_dir/label_example_gray_1.png
  tests/testdata/kmeans_classifier_gray_dir/label_example_gray_2.png
  tests/testdata/kmeans_classifier_gray_dir/label_example_gray_3.png
  tests/testdata/kmeans_classifier_gray_dir/labeled_image_gray.png
  tests/testdata/kmeans_classifier_gray_dir/test_image_gray.jpg
  tests/testdata/kmeans_train_gray_dir/kmeans_train_1_gray.jpg
  tests/testdata/kmeans_train_gray_dir/kmeans_train_2_gray.jpg
  tests/testdata/kmeans_train_gray_dir/kmeans_train_3_gray.jpg
  tests/testdata/kmeans_train_gray_dir/kmeans_train_4_gray.jpg
Labels: enhancement, ready to review

#1619 update prune _debug to plot the other debug img
  plantcv/plantcv/morphology/prune.py
Labels: ready to review, update, cleanup

#1609 Make color card chip size a metadata term & Enhance debug `pcv.transform.detect_color_card`
  docs/img/documentation_images/correct_color_imgs/detect_color_card.png
  docs/std_color_matrix.md
  docs/transform_detect_color_card.md
  plantcv/plantcv/transform/detect_color_card.py
Labels: enhancement, ready to review, update

#1627 Minor example code fix
  docs/updating.md
Labels: documentation, bugfix, ready to review

#1628 Update arabidopsis_multi_plant_tutorial.md
  docs/tutorials/arabidopsis_multi_plant_tutorial.md
Labels: documentation, ready to review

#1631 Update seed_analysis_tutorial.md
  docs/tutorials/seed_analysis_tutorial.md
Labels: documentation, ready to review

#1630 Update morphology_tutorial.md
  docs/tutorials/morphology_tutorial.md
Labels: documentation

#1632 Update watershed_segmentation_tutorial.md
  docs/tutorials/watershed_segmentation_tutorial.md
Labels: documentation
