Repository danforthcenter/plantcv, pull requests merged in 2024-03, with the labels that each got.

#1422 Correct camera distortions using checkerboard calibration
  docs/img/documentation_images/transform_camera_calibration/camera_calib_corrected.png
  docs/img/documentation_images/transform_camera_calibration/checkerboard_example.png
  docs/img/documentation_images/transform_camera_calibration/corners_registered_checkerboard.png
  docs/img/documentation_images/transform_camera_calibration/example_fisheye_plant.jpg
  docs/transform_calibrate_camera.md
  docs/transform_checkerboard_calibration.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/checkerboard_calib.py
  plantcv/plantcv/transform/warp.py
  tests/plantcv/transform/conftest.py
  tests/plantcv/transform/test_checkerboard_calib.py
  tests/testdata/checkerboard_imgdir/bad_checkerboard.png
  tests/testdata/checkerboard_imgdir/checkerboard1.png
  tests/testdata/checkerboard_imgdir/checkerboard2.png
  tests/testdata/checkerboard_imgdir/checkerboard3.png
  tests/testdata/checkerboard_imgdir/checkerboard4.png
  tests/testdata/checkerboard_imgdir/checkerboard5.png
  tests/testdata/checkerboard_imgdir/checkerboard6.png
  tests/testdata/checkerboard_imgdir/checkerboard7.png
  tests/testdata/checkerboard_imgdir/checkerboard8.png
  tests/testdata/checkerboard_imgdir/checkerboard9.png
  tests/testdata/dist.npz
  tests/testdata/fisheye_test_img.jpg
  tests/testdata/mtx.npz
Labels: new feature, ready to review

#1463 Improved handling of empty submasks in analyze.spectral_reflectance
  plantcv/plantcv/analyze/spectral_reflectance.py
Labels: enhancement, ready to review, update

#1458 Changed label from segment_sort output obs access to params value
  plantcv/plantcv/morphology/segment_sort.py
Labels: bugfix, ready to review

#1469 Run pytest on the whole project directory
  .github/workflows/continuous-integration.yml
Labels: bugfix, testing, ready to review

#1468 casted dict keys into list to avoid type error
  plantcv/utils/sample_images.py
Labels: bugfix, ready to review

#1471 Exclude configs from coverage analysis
  .deepsource.toml
  .github/workflows/continuous-integration.yml
Labels: bugfix

#1467 fixing assigning result of a function call with no return value
  tests/parallel/test_multiprocess.py
Labels: ready to review

#1472 Exclude more files from coverage analysis
  .deepsource.toml
Labels: bugfix

#1477 Add method to quickly filter binary images
  docs/roi_quick_filter.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/roi/__init__.py
  plantcv/plantcv/roi/quick_filter.py
  tests/plantcv/roi/test_quick_filter.py
Labels: new feature, ready to review

#1480 Fixed uninformative assert statements in tests for transform.merge_images()
  tests/plantcv/transform/test_merge_images.py
Labels: bugfix, ready to review
