Repository danforthcenter/plantcv, pull requests merged in 2024-07, with the labels that each got.

#1560 Pin NumPy to v1.x
  pyproject.toml
Labels: bugfix, ready to review

#1544 Using generators instead of list comprehension
  plantcv/plantcv/analyze/bound_horizontal.py
  plantcv/plantcv/analyze/bound_vertical.py
  plantcv/plantcv/analyze/size.py
  plantcv/plantcv/visualize/hyper_histogram.py
Labels: ready to review, cleanup

#1547 Adding missing docstrings
  plantcv/learn/cli.py
  plantcv/plantcv/classes.py
  plantcv/plantcv/create_labels.py
  plantcv/plantcv/roi/roi_methods.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/white_balance.py
  plantcv/utils/cli.py
  plantcv/utils/converters.py
  plantcv/utils/sample_images.py
Labels: ready to review, cleanup

#1542 Deepsource f string fix
  plantcv/parallel/parsers.py
Labels: ready to review, cleanup

#1543 Style fixes
  plantcv/plantcv/create_labels.py
  plantcv/plantcv/homology/landmark_reference_pt_dist.py
  tests/plantcv/io/conftest.py
  tests/plantcv/photosynthesis/conftest.py
  tests/plantcv/test_helper_iterate_analysis.py
  tests/plantcv/visualize/conftest.py
Labels: ready to review, cleanup

#1539 replacing implicit enumerate
  plantcv/utils/converters.py
Labels: ready to review, cleanup

#1530 add buttons to hyperspectral_smf_tutorial
  docs/tutorials/hyperspectral_smf_tutorial.md
  docs/tutorials/hyperspectral_tutorial.md
Labels: documentation, ready to review

#1528 Moved self's "n" attribute initialization to init
  plantcv/plantcv/classes.py
Labels: ready to review, cleanup

#1540 Unnecessary lambda removal
  plantcv/plantcv/visualize/obj_sizes.py
Labels: ready to review, cleanup

#1555 1553-combined-object-filter
  docs/filters_obj_props.md
  docs/img/documentation_images/filters_obj_props/example_barley_mask.png
  docs/img/documentation_images/filters_obj_props/example_filter_1.png
  docs/img/documentation_images/filters_obj_props/example_filter_2.png
  docs/img/documentation_images/filters_obj_props/example_filter_3.png
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/filters/__init__.py
  plantcv/plantcv/filters/obj_props.py
  tests/plantcv/filters/conftest.py
  tests/plantcv/filters/test_filter_objs.py
  tests/testdata/example_barley_mask.png
Labels: enhancement, new feature, ready to review

#1541 Constella reworks
  plantcv/plantcv/homology/constella.py
Labels: ready to review, cleanup

#1563 Suppress divide by zero and invalid number warnings
  plantcv/plantcv/spectral_index/spectral_index.py
Labels: enhancement, ready to review

#1565 Turn plotting off after use in tests to avoid warnings
  tests/plantcv/filters/test_filter_objs.py
  tests/plantcv/homology/test_acute.py
  tests/plantcv/test_debug.py
Labels: ready to review, cleanup

#1564 Fix casting issues that trigger NumPy deprecation warnings
  plantcv/plantcv/homology/constella.py
  plantcv/plantcv/homology/space.py
  plantcv/plantcv/morphology/analyze_stem.py
  plantcv/plantcv/morphology/segment_angle.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
Labels: ready to review, cleanup

#1562 auto_grid error handling
  plantcv/plantcv/roi/roi_methods.py
Labels: bugfix, ready to review
