Repository danforthcenter/plantcv, pull requests merged in 2024-05, with the labels that each got.

#1517 Clean up pytest errors
  .coveragerc
Labels: ready to review, cleanup

#1511 draw_roi bugfix
  docs/img/documentation_images/multi/custom_list_roi.png
  docs/img/documentation_images/multi/grid_roi.png
  plantcv/plantcv/roi/roi_methods.py
Labels: ready to review, update, cleanup

#1519 parallel docs for windows Update
  docs/parallel_config.md
  docs/roi_auto_grid.md
Labels: documentation, bugfix, ready to review, update, cleanup

#1482 Update watershed.py to make the function return `labels`
  docs/img/documentation_images/watershed/543_auto_cropped.jpg
  docs/img/documentation_images/watershed/cropped.jpg
  docs/img/documentation_images/watershed/mask.jpg
  docs/img/documentation_images/watershed/watershed.jpg
  docs/img/documentation_images/watershed/watershed_shape_measure.png
  docs/updating.md
  docs/watershed.md
  plantcv/plantcv/watershed.py
Labels: bugfix, ready to review, update

#1518 bugfix for roi_type="largest" in roi.filter
  plantcv/plantcv/_helpers.py
  tests/plantcv/roi/test_roi.py
Labels: bugfix, ready to review, update, merge in order

#1502 Adding simple rgb tutorial to the tutorial gallergy
  docs/tutorials.md
  docs/tutorials/simple_rgb_tutorial.md
  docs/tutorials/vis_tutorial.md
Labels: documentation, ready to review

#1506 Adding camera calibration tutorial
  docs/tutorials.md
  docs/tutorials/camera_calibration_tutorial.md
Labels: documentation

#1522 Added buttons to vis-nir tutorial
  docs/tutorials/vis_nir_tutorial.md
Labels: documentation
