Repository danforthcenter/plantcv, pull requests merged in 2024-12, with the labels that each got.

#1625 Auto color correct wrapper
  docs/transform_auto_correct_color.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/auto_correct_color.py
  tests/plantcv/transform/test_auto_correct_color.py
Labels: ready to review, update

#1616 1615 adding houghcircles
  docs/img/documentation_images/roi_auto_wells/21_roi.png
  docs/img/documentation_images/roi_auto_wells/circle-wells.png
  docs/roi_auto_wells.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/roi/__init__.py
  plantcv/plantcv/roi/roi_methods.py
  tests/conftest.py
  tests/plantcv/roi/test_roi.py
  tests/plantcv/test_helper_hough_circle.py
  tests/testdata/circle-wells.png
Labels: enhancement, new feature, ready to review

#1633 Update grayscale_tutorial.md
  docs/tutorials/grayscale_tutorial.md
Labels: documentation
