Repository danforthcenter/plantcv, pull requests merged in 2024-09, with the labels that each got.

#1587 update-to-jupyter-notebook-instructions
  docs/jupyter.md
Labels: documentation, ready to review

#1589 Fixed bug: crash when ROI was empty
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/analyze/spectral_index.py
Labels: bugfix, ready to review, update

#1595 Add metadata attribute to spectral_data class
  docs/Spectral_data.md
  plantcv/plantcv/classes.py
Labels: ready to review

#1593 Added NPCI and GLI indices to spectral_index
  docs/Spectral_data.md
  docs/spectral_index.md
  docs/updating.md
  plantcv/plantcv/spectral_index/__init__.py
  plantcv/plantcv/spectral_index/spectral_index.py
  tests/plantcv/spectral_index/test_spectral_index.py
Labels: new feature, ready to review, update

#1594 Add metadata to outputs
  plantcv/plantcv/analyze/size.py
  plantcv/plantcv/classes.py
  tests/plantcv/test_outputs.py
Labels: enhancement, ready to review, update

#1600 Update warn to utilize the verbose global parameter
  plantcv/plantcv/warn.py
  tests/plantcv/test_warn.py
Labels: enhancement, ready to review
