Repository danforthcenter/plantcv, pull requests merged in 2024-04, with the labels that each got.

#1478 Add kmeans classifier function
  docs/img/documentation_images/kmeans_clustering/leaf_background_mask.png
  docs/img/documentation_images/kmeans_clustering/leaf_example.png
  docs/img/documentation_images/kmeans_clustering/leaf_healthy_mask.png
  docs/img/documentation_images/kmeans_clustering/leaf_labeled.png
  docs/img/documentation_images/kmeans_clustering/leaf_sick_mask.png
  docs/kmeans_classifier.md
  docs/train_kmeans.md
  docs/transform_correct_color.md
  docs/updating.md
  mkdocs.yml
  plantcv/learn/__init__.py
  plantcv/learn/train_kmeans.py
  plantcv/plantcv/__init__.py
  plantcv/plantcv/kmeans_classifier.py
  tests/conftest.py
  tests/learn/conftest.py
  tests/learn/test_kmeans_train.py
  tests/plantcv/test_kmeans_classifier.py
  tests/testdata/kmeans_classifier_dir/combo_mask_example.png
  tests/testdata/kmeans_classifier_dir/kmeans_out.fit
  tests/testdata/kmeans_classifier_dir/label_example_0.png
  tests/testdata/kmeans_classifier_dir/label_example_1.png
  tests/testdata/kmeans_classifier_dir/label_example_2.png
  tests/testdata/kmeans_classifier_dir/label_example_3.png
  tests/testdata/kmeans_classifier_dir/labeled_image.png
  tests/testdata/kmeans_classifier_dir/test_image.jpg
  tests/testdata/kmeans_train_dir/kmeans_train_1.jpg
  tests/testdata/kmeans_train_dir/kmeans_train_2.jpg
  tests/testdata/kmeans_train_dir/kmeans_train_3.jpg
  tests/testdata/kmeans_train_dir/kmeans_train_4.jpg
Labels: new feature, ready to review

#1492 update _make_pseudo_rgb with more accurate target wavelength for red
  plantcv/plantcv/hyperspectral/read_data.py
Labels: bugfix, ready to review, update

#1496 Fix bug in plotting debug mode
  plantcv/learn/__init__.py
Labels: bugfix, ready to review

#1497 fix-PYL-W0612
  plantcv/plantcv/image_fusion.py
  plantcv/plantcv/morphology/segment_combine.py
  plantcv/plantcv/shift_img.py
  plantcv/plantcv/white_balance.py
Labels: ready to review, cleanup

#1457 Added fatal_error for incorrect block_size value in detect_color_card
  plantcv/plantcv/transform/detect_color_card.py
  tests/plantcv/transform/test_detect_color_card.py
Labels: ready to review, update, cleanup

#1495 Added tuple check to compare variables
  plantcv/plantcv/photosynthesis/reassign_frame_labels.py
  plantcv/plantcv/visualize/chlorophyll_fluorescence.py
Labels: ready to review, cleanup

#1448 Removed generator in threshold_methods.py
  plantcv/plantcv/threshold/threshold_methods.py
Labels: cleanup

#1499 Remove deprecated files
  masks/README.md
  masks/dev/plates/6well/6well_plate_roi.jpg
  masks/nir_tv/background_nir_z1000.png
  masks/nir_tv/background_nir_z3500.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h500_p1500_g100_163856_mask1.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h500_p1500_g100_163856_mask2.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h500_p1500_g100_163856_mask3.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h500_p1500_g100_163856_mask4.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h630_p1500_g100_163804_mask1.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h630_p1500_g100_163804_mask2.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h630_p1500_g100_163804_mask3.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h630_p1500_g100_163804_mask4.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h630_p1500_g100_163830_mask1.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h630_p1500_g100_163830_mask2.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h630_p1500_g100_163830_mask3.png
  masks/psII_tv/3d_plant_masks/PSII_TV_h630_p1500_g100_163830_mask4.png
  masks/psII_tv/PSII_z300_L1_mask.png
  masks/psII_tv/PSII_z500_mask.png
  masks/psII_tv/PSII_z630_L1_mask.png
  masks/vis_tv/mask_brass_tv_z1000_L1.png
  masks/vis_tv/mask_brass_tv_z1000_L2.png
  masks/vis_tv/mask_brass_tv_z1500_L1.png
  masks/vis_tv/mask_brass_tv_z1500_L2.png
  masks/vis_tv/mask_brass_tv_z1_L0.png
  masks/vis_tv/mask_brass_tv_z1_L1.png
  masks/vis_tv/mask_brass_tv_z2500_L1.png
  masks/vis_tv/mask_brass_tv_z2500_L2.png
  masks/vis_tv/mask_brass_tv_z3000_L1.png
  masks/vis_tv/mask_brass_tv_z300_L1.png
  masks/vis_tv/mask_brass_tv_z3500_L1.png
  masks/vis_tv/mask_brass_tv_z3500_L2.png
  masks/vis_tv/mask_brass_tv_z500_L2.png
  scripts/common.sh
  scripts/setup.sh
Labels: ready to review, cleanup

#1488 Rois debug numbering
  docs/img/documentation_images/multi/custom_list_roi.jpg
  docs/img/documentation_images/multi/custom_list_roi.png
  docs/img/documentation_images/multi/grid_roi.jpg
  docs/img/documentation_images/multi/grid_roi.png
  docs/img/documentation_images/multi/multi_plants_shape.jpg
  docs/img/documentation_images/multi/multi_plants_shape.png
  docs/img/documentation_images/multi/original_multi_image.jpg
  docs/params.md
  docs/roi_auto_grid.md
  docs/roi_multi.md
  plantcv/plantcv/classes.py
  plantcv/plantcv/roi/roi_methods.py
Labels: ready to review, update

#1505 Fixed error in documentation for camera calibration
  docs/transform_calibrate_camera.md
  docs/transform_checkerboard_calibration.md
Labels: documentation
