Repository danforthcenter/plantcv, pull requests merged in 2025-07, with the labels that each got.

#1734 Changes made to jupyter.md
  docs/jupyter.md
Labels: documentation

#1730 Quiet print statements from `pcv.homology.acute`
  docs/homology_acute.md
  plantcv/plantcv/homology/acute.py
Labels: ready to review, cleanup

#1726 Add support for automatic size scaling using color cards
  docs/analysis_approach.md
  docs/analyze_size.md
  docs/img/documentation_images/correct_color_imgs/calibrite-passport.png
  docs/img/documentation_images/correct_color_imgs/camera-trax.png
  docs/img/documentation_images/correct_color_imgs/classic.png
  docs/transform_auto_correct_color.md
  docs/transform_detect_color_card.md
  docs/updating.md
  plantcv/plantcv/transform/auto_correct_color.py
  plantcv/plantcv/transform/detect_color_card.py
  tests/plantcv/transform/test_detect_color_card.py
Labels: enhancement, new feature, ready to review, update
