Repository danforthcenter/plantcv, pull requests merged in 2025-05, with the labels that each got.

#1683 Add check to train kmeans that inputs must be np arrays
  docs/kmeans_classifier.md
  docs/train_kmeans.md
  plantcv/learn/train_kmeans.py
Labels: bugfix, ready to review

#1696 Morphology angle Outputs dtype bugfix
  plantcv/plantcv/morphology/segment_angle.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
Labels: bugfix, ready to review, update

#1702 Fix colors in `visualize.colorize_masks`
  plantcv/plantcv/visualize/colorize_masks.py
Labels: bugfix, ready to review

#1703 Update array stacking for color standard processing
  plantcv/plantcv/transform/color_correction.py
Labels: ready to review, update

#1644 Add `segment_ends` and Update morphology tips outputs
  docs/img/documentation_images/segment_ends/segment_end_pts.png
  docs/img/documentation_images/segment_ends/setaria_mask.png
  docs/segment_ends.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/morphology/__init__.py
  plantcv/plantcv/morphology/_iterative_prune.py
  plantcv/plantcv/morphology/analyze_stem.py
  plantcv/plantcv/morphology/find_tips.py
  plantcv/plantcv/morphology/prune.py
  plantcv/plantcv/morphology/segment_curvature.py
  plantcv/plantcv/morphology/segment_ends.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_id.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_sort.py
  plantcv/plantcv/morphology/segment_tangent_angle.py
  tests/plantcv/morphology/conftest.py
  tests/plantcv/morphology/test_prune.py
  tests/plantcv/morphology/test_segment_ends.py
  tests/testdata/morphology_disconnected_leaf.npz
  tests/testdata/morphology_disconnected_leaf_skel.png
Labels: new feature, bugfix, ready to review, update

#1708 Create helpers for color conversion
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/report_size_marker_area.py
  plantcv/plantcv/rgb2gray.py
  plantcv/plantcv/rgb2gray_cmyk.py
  plantcv/plantcv/rgb2gray_hsv.py
  plantcv/plantcv/rgb2gray_lab.py
  plantcv/plantcv/segment_image_series.py
  plantcv/plantcv/threshold/threshold_methods.py
  plantcv/plantcv/transform/checkerboard_calib.py
  plantcv/plantcv/transform/detect_color_card.py
  plantcv/plantcv/transform/nonuniform_illumination.py
  plantcv/plantcv/visualize/colorspaces.py
  plantcv/plantcv/visualize/pixel_scatter_vis.py
Labels: ready to review, cleanup
