Repository danforthcenter/plantcv, pull requests merged in 2025-06, with the labels that each got.

#1707 Add `pcv.transform.mask_color_card` function
  docs/img/documentation_images/transform_mask_color_card/seedhead-cleaned.png
  docs/img/documentation_images/transform_mask_color_card/seedhead-rgb.jpg
  docs/img/documentation_images/transform_mask_color_card/seedhead-with-cc.png
  docs/transform_mask_color_card.md
  docs/updating.md
  mkdocs.yml
  plantcv/plantcv/transform/__init__.py
  plantcv/plantcv/transform/detect_color_card.py
  tests/plantcv/transform/test_mask_color_card.py
Labels: new feature, ready to review, update

#1715 Create a logical operation helper function
  docs/logical_xor.md
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/kmeans_classifier.py
  plantcv/plantcv/logical_and.py
  plantcv/plantcv/logical_or.py
  plantcv/plantcv/logical_xor.py
  plantcv/plantcv/morphology/segment_insertion_angle.py
  plantcv/plantcv/morphology/segment_sort.py
  plantcv/plantcv/roi/quick_filter.py
  tests/plantcv/test_helper_logical_operation.py
Labels: ready to review, cleanup

#1725 Pin scipy to <1.16
  environment.yml
  pyproject.toml
Labels: bugfix, ready to review

#1717 Size scaling implementation in analysis functions
  docs/analyze_bound_horizontal2.md
  docs/analyze_bound_vertical2.md
  docs/analyze_stem.md
  docs/report_size_marker.md
  docs/segment_euclidean_length.md
  docs/segment_pathlength.md
  docs/transform_auto_correct_color.md
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/analyze/bound_horizontal.py
  plantcv/plantcv/analyze/bound_vertical.py
  plantcv/plantcv/analyze/size.py
  plantcv/plantcv/morphology/analyze_stem.py
  plantcv/plantcv/morphology/fill_segments.py
  plantcv/plantcv/morphology/segment_euclidean_length.py
  plantcv/plantcv/morphology/segment_path_length.py
Labels: enhancement, ready to review, update

#1720 `morphology.segment_skeleton` returned segment_objects to list
  plantcv/plantcv/morphology/segment_skeleton.py
Labels: bugfix, ready to review, update

#1723 Reduce cyclomatic complexity readbayer
  plantcv/plantcv/readbayer.py
  tests/plantcv/test_readbayer.py
Labels: ready to review, cleanup
