Repository danforthcenter/plantcv, pull requests merged in 2025-03, with the labels that each got.

#1656 updating install instructions
  docs/installation.md
Labels: documentation, ready to review

#1669 Update closing.py
  plantcv/plantcv/closing.py
Labels: enhancement, ready to review

#1657 Linking to scribe tutorial for parallelization
  docs/pipeline_parallel.md
Labels: documentation, ready to review

#1659 updating the getting started page
  docs/index.md
  docs/jupyter.md
Labels: documentation, ready to review

#1670 Update crop_position_mask.py
  plantcv/plantcv/crop_position_mask.py
  tests/plantcv/test_crop_position_mask.py
Labels: bug, enhancement, ready to review

#1673 add `metadata` to `_package_index` in spectral_index.py
  plantcv/plantcv/spectral_index/spectral_index.py
  tests/testdata/hsi.pkl
Labels: bugfix, ready to review, update

#1681 Update PlantCV installation instructions and conda environment file to use only the conda-forge channel
  docs/installation.md
  environment.yml
Labels: documentation, ready to review

#1642 add tassel tutorial to gallery (merge updates to tutorial repo first)
  docs/tutorials.md
  docs/tutorials/tassel_tutorial.md
Labels: documentation, ready to review

#1680 Added background image input to visualize.pseudocolor
  docs/img/documentation_images/pseudocolor/pseudo_on_rgb_image.png
  docs/img/documentation_images/pseudocolor/pseudocolored_mask_bad.png
  docs/visualize_pseudocolor.md
  plantcv/plantcv/visualize/pseudocolor.py
  tests/plantcv/visualize/conftest.py
  tests/plantcv/visualize/test_pseudocolor.py
Labels: enhancement, ready to review, update
