Repository danforthcenter/plantcv, pull requests merged in 2025-02, with the labels that each got.

#1668 Update d type in fill_holes.py check
  plantcv/plantcv/fill_holes.py
Labels: ready to review

#1664 Add deprecation warning about `label` from the detect color card function
  plantcv/plantcv/transform/auto_correct_color.py
  plantcv/plantcv/transform/detect_color_card.py
Labels: bugfix, ready to review, update, cleanup

#1653 Parallelization docs linking
  docs/parallel_config.md
  docs/pipeline_parallel.md
Labels: documentation, ready to review

#1648 Fix mask kmeans output type
  docs/kmeans_classifier.md
  plantcv/plantcv/kmeans_classifier.py
Labels: bugfix, ready to review
