Repository danforthcenter/plantcv, pull requests merged in 2025-08, with the labels that each got.

#1731 Regional filter for color card detection
  docs/transform_auto_correct_color.md
  docs/transform_detect_color_card.md
  docs/updating.md
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/transform/auto_correct_color.py
  plantcv/plantcv/transform/detect_color_card.py
  tests/plantcv/test_helper_rect_filter.py
  tests/plantcv/test_helper_rect_replace.py
  tests/plantcv/transform/test_auto_correct_color.py
Labels: enhancement, ready to review

#1740 General rect filter
  docs/closing.md
  docs/dilate.md
  docs/erode.md
  docs/fill.md
  docs/fill_holes.md
  docs/filters_obj_props.md
  docs/floodfill.md
  docs/gaussian_blur.md
  docs/laplace_filter.md
  docs/median_blur.md
  docs/opening.md
  docs/scharr_filter.md
  docs/sobel_filter.md
  docs/stdev_filter.md
  docs/updating.md
  plantcv/plantcv/_helpers.py
  plantcv/plantcv/closing.py
  plantcv/plantcv/dilate.py
  plantcv/plantcv/erode.py
  plantcv/plantcv/fill.py
  plantcv/plantcv/fill_holes.py
  plantcv/plantcv/filters/obj_props.py
  plantcv/plantcv/floodfill.py
  plantcv/plantcv/gaussian_blur.py
  plantcv/plantcv/laplace_filter.py
  plantcv/plantcv/median_blur.py
  plantcv/plantcv/opening.py
  plantcv/plantcv/scharr_filter.py
  plantcv/plantcv/sobel_filter.py
  plantcv/plantcv/stdev_filter.py
  tests/plantcv/filters/test_filter_objs.py
  tests/plantcv/test_closing.py
  tests/plantcv/test_dilate.py
  tests/plantcv/test_erode.py
  tests/plantcv/test_fill.py
  tests/plantcv/test_fill_holes.py
  tests/plantcv/test_floodfill.py
  tests/plantcv/test_gaussian_blur.py
  tests/plantcv/test_laplace_filter.py
  tests/plantcv/test_median_blur.py
  tests/plantcv/test_opening.py
  tests/plantcv/test_scharr_filter.py
  tests/plantcv/test_sobel_filter.py
  tests/plantcv/test_stdev_filter.py
  tests/plantcv/transform/test_auto_correct_color.py
Labels: enhancement, ready to review

#1732 Add color card detection squareness parameters
  docs/transform_auto_correct_color.md
  docs/transform_detect_color_card.md
  plantcv/plantcv/transform/auto_correct_color.py
  plantcv/plantcv/transform/detect_color_card.py
Labels: enhancement, ready to review, update

#1745 Check color card squares
  plantcv/plantcv/transform/detect_color_card.py
  tests/plantcv/transform/conftest.py
  tests/plantcv/transform/test_detect_color_card.py
  tests/testdata/partial_card_rgb.png
Labels: enhancement, ready to review

#1748 add nano color card support in size scaling
  docs/img/documentation_images/correct_color_imgs/nano.jpeg
  docs/transform_auto_correct_color.md
  docs/transform_detect_color_card.md
  plantcv/plantcv/transform/detect_color_card.py
Labels: enhancement, ready to review

#1752 Update kmeans inputs
  plantcv/plantcv/kmeans_classifier.py
  tests/plantcv/test_kmeans_classifier.py
Labels: enhancement, ready to review

#1755 fixing typo
  plantcv/plantcv/closing.py
Labels: ready to review

#1758 Hough circle regional filter
  docs/roi_auto_wells.md
  docs/updating.md
  plantcv/plantcv/roi/roi_methods.py
  tests/plantcv/roi/test_roi.py
Labels: enhancement, ready to review

#1762 update FAQ to mention color standardization
  docs/analysis_approach.md
  docs/faq.md
  docs/transform_detect_color_card.md
Labels: documentation, ready to review

#1769 Use a self-hosted image for testing
  tests/plantcv/io/test_open_url.py
Labels: bugfix, ready to review

#1763 Add cymk threshold custom range
  docs/custom_range_threshold.md
  plantcv/plantcv/threshold/threshold_methods.py
  tests/plantcv/threshold/test_threshold_methods.py
Labels: enhancement, ready to review
